# This file is automatically generated by pyo3_stub_gen
from typing import Any

__all__ = [
    "get_structure_metadata",
]

def get_structure_metadata(structure: str | dict[str, Any]) -> dict:
    r"""
    Get structure metadata.
    """
