# This file is automatically generated by pyo3_stub_gen
from typing import Any

def get_structure_metadata(structure: str | dict[str, Any]) -> dict[str, Any]:
    r"""
    Get structure metadata.
    """
