// Three.js scene → STL / OBJ+MTL / GLB download, shared by the Fermi surface, structure and
// chemical potential exporters. The exporters are lazy-imported so viewers that never export
// don't ship them.
import { download } from '$lib/io/fetch'
import { clamp01, to_error } from '$lib/utils'
import type { BufferGeometry, InstancedMesh, Material, Object3D } from 'three/webgpu'
import {
  Color,
  Group,
  Matrix4,
  Mesh,
  MeshStandardMaterial,
  SRGBColorSpace,
} from 'three/webgpu'

export type SceneExportFormat = `stl` | `obj` | `glb`

// Type guard to check if a material has a Color-like property with numeric r/g/b
// channels (duck typing for bundler compatibility across different Three.js
// instances - Threlte vs vanilla Three.js).
function has_color_property(mat: Material): mat is Material & { color: Color } {
  const color = (mat as { color?: unknown }).color
  if (!color || typeof color !== `object`) return false
  const { r: red, g: green, b: blue } = color as { r?: unknown; g?: unknown; b?: unknown }
  return typeof red === `number` && typeof green === `number` && typeof blue === `number`
}

// Identifies gradient bond meshes (structure viewer). Their two per-instance colors live in
// these geometry attributes and are consumed by a TSL node graph, so unlike ordinary meshes
// their color cannot be read off the material — it has to be recovered from the attributes.
const has_bond_gradient_attributes = (geometry: BufferGeometry): boolean =>
  Boolean(
    geometry.getAttribute(`instanceColorStart`) && geometry.getAttribute(`instanceColorEnd`),
  )

// Midpoint of a gradient bond's start and end colors for one instance
function extract_bond_color_for_instance(
  geometry: BufferGeometry,
  instance_idx: number,
): Color | null {
  const color_start_attr = geometry.getAttribute(`instanceColorStart`)
  const color_end_attr = geometry.getAttribute(`instanceColorEnd`)

  if (!color_start_attr || !color_end_attr) return null
  if (instance_idx < 0 || instance_idx >= color_start_attr.count) return null

  return new Color(
    (color_start_attr.getX(instance_idx) + color_end_attr.getX(instance_idx)) / 2,
    (color_start_attr.getY(instance_idx) + color_end_attr.getY(instance_idx)) / 2,
    (color_start_attr.getZ(instance_idx) + color_end_attr.getZ(instance_idx)) / 2,
  )
}

// Remove per-instance and non-standard color attributes that cause export issues.
function clean_geometry_for_export(geometry: BufferGeometry): void {
  for (const attr_name of Object.keys(geometry.attributes)) {
    const lower_name = attr_name.toLowerCase()
    if (
      lower_name.includes(`instance`) ||
      (lower_name.includes(`color`) && lower_name !== `color`)
    )
      geometry.deleteAttribute(attr_name)
  }
}

// Generate MTL (Wavefront Material) content from scene materials.
export function generate_mtl_content(scene: Object3D): string {
  const lines: string[] = [`# MTL file generated by MatterViz`, ``]
  const processed_materials = new Set<string>()
  // MTL carries no color space, but three's own MTLLoader reads Kd/Ka as sRGB, so emitting a
  // material's working-space channels verbatim round-trips ~2x too dark. Converted through a
  // Color we own because has_color_property only duck-types r/g/b off foreign three instances.
  const srgb_color = new Color()
  const fmt = (val: number) => clamp01(val).toFixed(6)
  // `scale` is applied in linear light before encoding — 20% ambient reflectance means 20% of
  // the linear diffuse, and scaling the encoded value instead would yield about 4%.
  const encode_srgb = (color: { r: number; g: number; b: number }, scale: number): string => {
    srgb_color.setRGB(color.r * scale, color.g * scale, color.b * scale)
    const { r: red, g: green, b: blue } = srgb_color.getRGB(srgb_color, SRGBColorSpace)
    return `${fmt(red)} ${fmt(green)} ${fmt(blue)}`
  }

  scene.traverse((object) => {
    if (!(object instanceof Mesh)) return

    const materials = Array.isArray(object.material) ? object.material : [object.material]
    for (const mat of materials) {
      // Skip if already processed or no name
      // oxlint-disable-next-line @typescript-eslint/prefer-nullish-coalescing -- empty name should use default
      const mat_name = mat.name || `default_material`
      if (processed_materials.has(mat_name)) continue
      processed_materials.add(mat_name)

      lines.push(`newmtl ${mat_name}`)

      // Get diffuse color (main color), defaulting to white
      const color = has_color_property(mat) ? mat.color : { r: 1, g: 1, b: 1 }
      lines.push(
        `Kd ${encode_srgb(color, 1)}`,
        `Ka ${encode_srgb(color, 0.2)}`, // Ambient is typically a fraction of diffuse
        `Ks 0.500000 0.500000 0.500000`,
        `Ns 96.078431`, // Specular exponent
      )

      // Transparency (d = 1.0 is fully opaque)
      const opacity = `opacity` in mat && typeof mat.opacity === `number` ? mat.opacity : 1.0
      lines.push(
        `d ${opacity.toFixed(6)}`,
        `illum 2`, // Illumination model (2 = highlight on)
        ``,
      )
    }
  })

  return lines.join(`\n`)
}

// Type guard for InstancedMesh (Three.js uses isInstancedMesh property, not exposed in
// Object3D type). Threlte's InstancedMesh sets isInstancedMesh=true but type stays "Mesh".
const is_instanced_mesh = (obj: Object3D): obj is InstancedMesh =>
  (obj as InstancedMesh).isInstancedMesh || obj.type === `InstancedMesh`

// Copy of `scene` with every InstancedMesh expanded into a Group of plain Meshes (one per
// instance, carrying its resolved color), since the GLB/OBJ exporters don't handle instancing
export function convert_instanced_meshes_to_regular<T extends Object3D>(scene: T): T {
  const cloned_scene = scene.clone()
  const cloned_meshes: InstancedMesh[] = []
  cloned_scene.traverse((object) => {
    if (is_instanced_mesh(object)) cloned_meshes.push(object)
  })

  for (const [mesh_idx, instanced_mesh] of cloned_meshes.entries()) {
    const parent = instanced_mesh.parent
    if (!parent || !instanced_mesh.instanceMatrix) continue

    // Create a group to hold all the individual meshes
    const group = new Group()
    group.name = instanced_mesh.name

    const has_bond_gradient = has_bond_gradient_attributes(instanced_mesh.geometry)
    const { instanceColor: instance_color_attr } = instanced_mesh
    const source_material = Array.isArray(instanced_mesh.material)
      ? instanced_mesh.material[0]
      : instanced_mesh.material
    const material_color = has_color_property(source_material) ? source_material.color : null
    const material_tint = material_color ?? new Color(1, 1, 1)

    // One geometry clone shared by every instance mesh (the exporters dedupe shared
    // buffers; a 10k-atom scene must not clone 10k geometries). Instance color attributes
    // have one entry per bond, not per vertex, so they break GLTF accessor-count validation
    // once instances become standalone meshes — strip them from the clone once.
    const shared_geometry = instanced_mesh.geometry.clone()
    if (has_bond_gradient) clean_geometry_for_export(shared_geometry)

    // Materials: fresh MeshStandardMaterial for reliability, one per instance only when a
    // per-instance colour resolves, otherwise one shared material in the base colour
    const make_material = (name: string, color: Color | null): MeshStandardMaterial => {
      const material = new MeshStandardMaterial({ metalness: 0.1, roughness: 0.5 })
      material.name = name
      if (color) material.color.copy(color)
      return material
    }
    const per_instance_color = has_bond_gradient || instance_color_attr !== null
    const shared_material = per_instance_color
      ? null
      : make_material(`material_${mesh_idx}`, material_color)

    // Create individual meshes for each instance
    const instance_color = new Color()
    const instance_matrix = new Matrix4()
    const combined_matrix = new Matrix4()
    for (let idx = 0; idx < instanced_mesh.count; idx++) {
      instanced_mesh.getMatrixAt(idx, instance_matrix)

      const resolved_color = has_bond_gradient
        ? extract_bond_color_for_instance(instanced_mesh.geometry, idx)
        : instance_color_attr
          ? instance_color
              .fromBufferAttribute(instance_color_attr, idx)
              .multiply(material_tint)
          : material_color
      const material =
        shared_material ?? make_material(`material_${mesh_idx}_${idx}`, resolved_color)

      const mesh = new Mesh(shared_geometry, material)

      // Combine base transform with instance transform
      combined_matrix.multiplyMatrices(instanced_mesh.matrix, instance_matrix)
      mesh.applyMatrix4(combined_matrix)

      group.add(mesh)
    }

    // Replace the InstancedMesh with the Group in the parent
    parent.remove(instanced_mesh)
    parent.add(group)
  }

  // Update all world matrices in the modified scene
  cloned_scene.updateMatrixWorld(true)

  // Strip leftover per-instance color attributes from any mesh the instancing pass didn't
  // rewrite, so they can't trip GLTF accessor-count validation.
  cloned_scene.traverse((object) => {
    if (object instanceof Mesh && has_bond_gradient_attributes(object.geometry)) {
      object.geometry = object.geometry.clone()
      clean_geometry_for_export(object.geometry)
    }
  })

  return cloned_scene
}

// Download `scene` as `<basename>.<format>`. OBJ also downloads a companion `.mtl` carrying
// the material colors; GLB is binary glTF (materials and colors embedded). Instanced meshes are
// expanded first since none of three's exporters handle instancing. Rejects on exporter errors.
export async function export_scene_as(
  scene: Object3D,
  format: SceneExportFormat,
  basename: string,
): Promise<void> {
  const export_root = convert_instanced_meshes_to_regular(scene)
  if (format === `stl`) {
    const { STLExporter } = await import(`three/examples/jsm/exporters/STLExporter.js`)
    const result = new STLExporter().parse(export_root, { binary: true })
    // Binary STL returns DataView, convert to ArrayBuffer for Blob
    const buffer = result instanceof DataView ? result.buffer : result
    download(buffer, `${basename}.stl`, `application/octet-stream`)
  } else if (format === `obj`) {
    const { OBJExporter } = await import(`three/examples/jsm/exporters/OBJExporter.js`)
    const mtl_filename = `${basename}.mtl`
    // Material library reference goes at the top of the OBJ file
    const obj_content = `mtllib ${mtl_filename}\n${new OBJExporter().parse(export_root)}`
    download(obj_content, `${basename}.obj`, `text/plain`)
    // Small delay to prevent some browsers from blocking rapid successive downloads as
    // potential abuse. A more robust solution might be to zip both files together.
    const mtl_content = generate_mtl_content(export_root)
    setTimeout(() => download(mtl_content, mtl_filename, `text/plain`), 100)
  } else if (format === `glb`) {
    const { GLTFExporter } = await import(`three/examples/jsm/exporters/GLTFExporter.js`)
    await new Promise<void>((resolve, reject) => {
      new GLTFExporter().parse(
        export_root,
        (result) => {
          if (!(result instanceof ArrayBuffer)) {
            reject(new Error(`GLB export returned ${typeof result} instead of ArrayBuffer`))
            return
          }
          download(result, `${basename}.glb`, `model/gltf-binary`)
          resolve()
        },
        (error) => reject(to_error(error)),
        { binary: true },
      )
    })
  } else throw new Error(`Unsupported scene export format: ${format}`)
}
