name: Feature Request
description: Suggest an idea for MatterViz
labels: ['enhancement']
body:
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: |
        **📓 Python/Jupyter Notebook Users:** Please submit your request at [pymatviz](https://github.com/janosh/pymatviz) instead.

        **Everyone else:** Please describe:
        - The feature you'd like to see
        - Why you need it
        - How it would work
      placeholder: Describe your feature request
    validations:
      required: true
