// Stub file - this will be overwritten when WASM is built via `pnpm build` in extensions/rust-wasm
// The actual WASM module is generated by wasm-pack from extensions/rust

const STUB_ERROR =
  `ferrox-wasm not built. Run 'cd extensions/rust-wasm && pnpm build' to compile the WASM module.`

export default function init() {
  return Promise.reject(new Error(STUB_ERROR))
}

export class WasmStructureMatcher {
  constructor() {
    throw new Error(STUB_ERROR)
  }
}

// Export stubs for all functions to prevent import errors
export const parse_structure = () => {
  throw new Error(STUB_ERROR)
}
export const parse_cif = () => {
  throw new Error(STUB_ERROR)
}
export const parse_poscar = () => {
  throw new Error(STUB_ERROR)
}
export const make_supercell_diag = () => {
  throw new Error(STUB_ERROR)
}
export const make_supercell = () => {
  throw new Error(STUB_ERROR)
}
export const get_reduced_structure = () => {
  throw new Error(STUB_ERROR)
}
export const get_primitive = () => {
  throw new Error(STUB_ERROR)
}
export const get_spacegroup_number = () => {
  throw new Error(STUB_ERROR)
}
export const structure_to_json = () => {
  throw new Error(STUB_ERROR)
}
export const get_volume = () => {
  throw new Error(STUB_ERROR)
}
export const get_total_mass = () => {
  throw new Error(STUB_ERROR)
}
export const get_density = () => {
  throw new Error(STUB_ERROR)
}
export const get_neighbor_list = () => {
  throw new Error(STUB_ERROR)
}
export const get_distance = () => {
  throw new Error(STUB_ERROR)
}
export const get_distance_matrix = () => {
  throw new Error(STUB_ERROR)
}
export const get_sorted_structure = () => {
  throw new Error(STUB_ERROR)
}
export const get_sorted_by_electronegativity = () => {
  throw new Error(STUB_ERROR)
}
export const interpolate_structures = () => {
  throw new Error(STUB_ERROR)
}
export const copy_structure = () => {
  throw new Error(STUB_ERROR)
}
export const wrap_to_unit_cell = () => {
  throw new Error(STUB_ERROR)
}
export const translate_sites = () => {
  throw new Error(STUB_ERROR)
}
export const perturb_structure = () => {
  throw new Error(STUB_ERROR)
}
export const get_atomic_mass = () => {
  throw new Error(STUB_ERROR)
}
export const get_electronegativity = () => {
  throw new Error(STUB_ERROR)
}
