import { get_electro_neg_formula } from '$lib/composition'
import { download } from '$lib/io/fetch'
import type { Vec3 } from '$lib/math'
import * as math from '$lib/math'
import type { AnyStructure, Site } from '$lib/structure'
import { is_plain_object } from '$lib/utils'
import type { BufferGeometry, InstancedMesh, Material, Object3D, Scene } from 'three/webgpu'
import {
  Color,
  Group,
  Matrix4,
  Mesh,
  MeshStandardMaterial,
  SRGBColorSpace,
} from 'three/webgpu'
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js'
import { OBJExporter } from 'three/examples/jsm/exporters/OBJExporter.js'

// @internal exported only for tests - not part of the public API.
// Type guard to check if a material has a Color-like property with numeric r/g/b
// channels (duck typing for bundler compatibility across different Three.js
// instances - Threlte vs vanilla Three.js).
export function has_color_property(mat: Material): mat is Material & { color: Color } {
  const color = (mat as { color?: unknown }).color
  if (!color || typeof color !== `object`) return false
  const { r: red, g: green, b: blue } = color as { r?: unknown; g?: unknown; b?: unknown }
  return typeof red === `number` && typeof green === `number` && typeof blue === `number`
}

// @internal exported only for tests - not part of the public API.
// Identifies gradient bond meshes. Their two per-instance colors live in these geometry
// attributes and are consumed by a TSL node graph, so unlike ordinary meshes their color
// cannot be read off the material — it has to be recovered from the attributes below.
export const has_bond_gradient_attributes = (geometry: BufferGeometry): boolean =>
  Boolean(
    geometry.getAttribute(`instanceColorStart`) && geometry.getAttribute(`instanceColorEnd`),
  )

// @internal exported only for tests - not part of the public API.
// Extract bond gradient colors from geometry attributes for a specific instance.
// Returns midpoint color between start and end colors for the bond.
export function extract_bond_color_for_instance(
  geometry: BufferGeometry,
  instance_idx: number,
): Color | null {
  const color_start_attr = geometry.getAttribute(`instanceColorStart`)
  const color_end_attr = geometry.getAttribute(`instanceColorEnd`)

  if (!color_start_attr || !color_end_attr) return null
  if (instance_idx < 0 || instance_idx >= color_start_attr.count) return null

  // Get RGB values for this instance and compute midpoint color
  const start_rgb: Vec3 = [
    color_start_attr.getX(instance_idx),
    color_start_attr.getY(instance_idx),
    color_start_attr.getZ(instance_idx),
  ]
  const end_rgb: Vec3 = [
    color_end_attr.getX(instance_idx),
    color_end_attr.getY(instance_idx),
    color_end_attr.getZ(instance_idx),
  ]
  const [mid_r, mid_g, mid_b] = math.scale(math.add(start_rgb, end_rgb), 0.5)
  return new Color(mid_r, mid_g, mid_b)
}

// @internal exported only for tests - not part of the public API.
// Remove custom/non-standard attributes from geometry that cause export issues.
// Standard GLTF attributes: position, normal, tangent, texcoord_N, color_N, joints_N,
// weights_N.
export function clean_geometry_for_export(geometry: BufferGeometry): void {
  const standard_attrs = new Set([
    `position`,
    `normal`,
    `tangent`,
    `uv`,
    `uv1`,
    `uv2`,
    `uv3`,
    `color`,
    `skinIndex`,
    `skinWeight`,
  ])

  const attrs_to_remove: string[] = []
  for (const attr_name of Object.keys(geometry.attributes)) {
    // Keep standard attributes and those starting with underscore (GLTF custom)
    // But remove instance-specific attributes that cause accessor count mismatches
    const lower_name = attr_name.toLowerCase()
    if (
      lower_name.includes(`instance`) ||
      (lower_name.includes(`color`) && !standard_attrs.has(lower_name))
    )
      attrs_to_remove.push(attr_name)
  }

  for (const attr_name of attrs_to_remove) {
    geometry.deleteAttribute(attr_name)
  }
}

// @internal exported only for tests - not part of the public API.
// Generate MTL (Wavefront Material) content from scene materials.
export function generate_mtl_content(scene: Scene): string {
  const lines: string[] = [`# MTL file generated by MatterViz`, ``]
  const processed_materials = new Set<string>()
  // MTL carries no color space, but three's own MTLLoader reads Kd/Ka as sRGB, so emitting a
  // material's working-space channels verbatim round-trips ~2x too dark. Converted through a
  // Color we own because has_color_property only duck-types r/g/b off foreign three instances.
  const srgb_color = new Color()
  const fmt = (val: number) => Math.min(1, Math.max(0, val)).toFixed(6)
  // `scale` is applied in linear light before encoding — 20% ambient reflectance means 20% of
  // the linear diffuse, and scaling the encoded value instead would yield about 4%.
  const encode_srgb = (color: { r: number; g: number; b: number }, scale: number): string => {
    srgb_color.setRGB(color.r * scale, color.g * scale, color.b * scale)
    const { r: red, g: green, b: blue } = srgb_color.getRGB(srgb_color, SRGBColorSpace)
    return `${fmt(red)} ${fmt(green)} ${fmt(blue)}`
  }

  scene.traverse((object) => {
    if (!(object instanceof Mesh)) return

    const materials = Array.isArray(object.material) ? object.material : [object.material]
    for (const mat of materials) {
      // Skip if already processed or no name
      // oxlint-disable-next-line @typescript-eslint/prefer-nullish-coalescing -- empty name should use default
      const mat_name = mat.name || `default_material`
      if (processed_materials.has(mat_name)) continue
      processed_materials.add(mat_name)

      lines.push(`newmtl ${mat_name}`)

      // Get diffuse color (main color), defaulting to white
      const color = has_color_property(mat) ? mat.color : { r: 1, g: 1, b: 1 }
      lines.push(`Kd ${encode_srgb(color, 1)}`)
      // Ambient is typically a fraction of diffuse
      lines.push(`Ka ${encode_srgb(color, 0.2)}`)

      // Specular properties
      lines.push(`Ks 0.500000 0.500000 0.500000`)
      lines.push(`Ns 96.078431`) // Specular exponent

      // Transparency (d = 1.0 is fully opaque)
      const opacity = `opacity` in mat && typeof mat.opacity === `number` ? mat.opacity : 1.0
      lines.push(`d ${opacity.toFixed(6)}`)

      // Illumination model (2 = highlight on)
      lines.push(`illum 2`)
      lines.push(``)
    }
  })

  return lines.join(`\n`)
}

// Helper function to convert InstancedMesh to regular Mesh objects for export
// This is necessary because GLB/OBJ exporters don't handle InstancedMesh properly
// Note: Threlte's InstancedMesh sets isInstancedMesh=true but type remains "Mesh"
// Type guard for InstancedMesh (Three.js uses isInstancedMesh property, not exposed in Object3D type)
const is_instanced_mesh = (obj: Object3D): obj is InstancedMesh =>
  (obj as InstancedMesh).isInstancedMesh || obj.type === `InstancedMesh`

// @internal exported only for tests - not part of the public API.
export function convert_instanced_meshes_to_regular(scene: Scene): Scene {
  const cloned_scene = scene.clone()
  const cloned_meshes: InstancedMesh[] = []
  cloned_scene.traverse((object) => {
    if (is_instanced_mesh(object)) cloned_meshes.push(object)
  })

  for (const [mesh_idx, instanced_mesh] of cloned_meshes.entries()) {
    const parent = instanced_mesh.parent
    if (!parent || !instanced_mesh.instanceMatrix) continue

    // Create a group to hold all the individual meshes
    const group = new Group()
    group.name = instanced_mesh.name

    // Get the base transform from the InstancedMesh
    const base_matrix = new Matrix4()
    base_matrix.copy(instanced_mesh.matrix)

    const has_bond_gradient = has_bond_gradient_attributes(instanced_mesh.geometry)
    const { instanceColor } = instanced_mesh
    const source_material = Array.isArray(instanced_mesh.material)
      ? instanced_mesh.material[0]
      : instanced_mesh.material
    const material_color = has_color_property(source_material) ? source_material.color : null
    let all_instance_colors_are_white = Boolean(instanceColor)
    if (instanceColor) {
      const instance_color = new Color()
      const white = new Color(1, 1, 1)
      for (let instance_idx = 0; instance_idx < instanced_mesh.count; instance_idx++) {
        instance_color.fromBufferAttribute(instanceColor, instance_idx)
        if (!instance_color.equals(white)) {
          all_instance_colors_are_white = false
          break
        }
      }
    }
    // Threlte's legacy instancing stores the real color on the material and an
    // all-white instanceColor buffer. Real per-instance colors take precedence otherwise.
    const use_material_color =
      all_instance_colors_are_white &&
      material_color !== null &&
      !material_color.equals(new Color(1, 1, 1))

    // Create individual meshes for each instance
    const instance_matrix = new Matrix4()
    for (let idx = 0; idx < instanced_mesh.count; idx++) {
      instanced_mesh.getMatrixAt(idx, instance_matrix)

      // Clone geometry
      const cloned_geometry = instanced_mesh.geometry.clone()

      // Instance color attributes have one entry per bond, not per vertex, so they break
      // GLTF accessor-count validation once instances become standalone meshes.
      if (has_bond_gradient) {
        clean_geometry_for_export(cloned_geometry)
      }

      // Create material - always create fresh MeshStandardMaterial for reliability
      const new_material = new MeshStandardMaterial({
        metalness: 0.1,
        roughness: 0.5,
      })
      new_material.name = `material_${mesh_idx}_${idx}`

      const resolved_color = has_bond_gradient
        ? extract_bond_color_for_instance(instanced_mesh.geometry, idx)
        : instanceColor && !use_material_color
          ? new Color().fromBufferAttribute(instanceColor, idx)
          : material_color
      if (resolved_color) new_material.color.copy(resolved_color)

      const mesh = new Mesh(cloned_geometry, new_material)

      // Combine base transform with instance transform
      const combined_matrix = new Matrix4()
      combined_matrix.multiplyMatrices(base_matrix, instance_matrix)
      mesh.applyMatrix4(combined_matrix)

      group.add(mesh)
    }

    // Replace the InstancedMesh with the Group in the parent
    parent.remove(instanced_mesh)
    parent.add(group)

    // Update world matrices after scene graph modification
    group.updateMatrixWorld(true)
  }

  // Update all world matrices in the modified scene
  cloned_scene.updateMatrixWorld(true)

  // Strip leftover per-instance color attributes from any mesh the instancing pass didn't
  // rewrite, so they can't trip GLTF accessor-count validation.
  cloned_scene.traverse((object) => {
    if (object instanceof Mesh && has_bond_gradient_attributes(object.geometry)) {
      clean_geometry_for_export(object.geometry)
    }
  })

  return cloned_scene
}

// Generate a filename for structure exports based on structure metadata
// Sanitize string for use in filenames by removing problematic characters.
const sanitize_filename_part = (text: string): string =>
  text
    .replaceAll(/<\/?[^>]+>/g, ``) // strip HTML tags
    .replaceAll(/[/\\:*?"<>|]/g, `_`) // replace filesystem-invalid chars
    .replaceAll(/_+/g, `_`) // condense consecutive underscores
    .replaceAll(/^_|_$/g, ``) // remove leading/trailing underscores

export function create_structure_filename(
  structure: AnyStructure | undefined,
  extension: string,
): string {
  if (!structure) return `structure.${extension}`

  const parts: string[] = []
  // Helper to sanitize and push non-empty parts
  const safe_push = (value: string | undefined) => {
    const sanitized = value ? sanitize_filename_part(value) : ``
    if (sanitized) parts.push(sanitized)
  }
  safe_push(structure.id)

  // Add formula (plain text to avoid HTML in filenames)
  const formula = get_electro_neg_formula(structure, true)
  if (formula && formula !== `Unknown`) {
    safe_push(formula.replaceAll(` `, ``))
  }

  // Add space group and lattice system if available
  const symmetry =
    `symmetry` in structure && is_plain_object(structure.symmetry)
      ? structure.symmetry
      : undefined
  if (typeof symmetry?.space_group_symbol === `string`) {
    safe_push(symmetry.space_group_symbol.replaceAll(` `, ``))
  }
  const lattice =
    `lattice` in structure && is_plain_object(structure.lattice)
      ? structure.lattice
      : undefined
  if (lattice && `lattice_system` in lattice && typeof lattice.lattice_system === `string`)
    safe_push(lattice.lattice_system)

  // Add number of sites
  if (structure.sites?.length) parts.push(`${structure.sites.length}sites`)

  const base_name = parts.length > 0 ? parts.join(`-`) : `structure`
  return `${base_name}.${extension}`
}

// First species' element of a site, or `X` when the site has no species
const site_element = (site: Site): string => site.species?.[0]?.element || `X`

// Fractional coordinates from abc, falling back to converting xyz; throws when neither
// is available. idx (when given) is included in the error message.
function get_frac_coords(
  site: Site,
  cart_to_frac: ((xyz: Vec3) => Vec3) | null,
  idx?: number,
): number[] {
  if (Array.isArray(site.abc) && site.abc.length >= 3) return site.abc.slice(0, 3)
  if (site.xyz?.length >= 3 && cart_to_frac) return cart_to_frac(site.xyz.slice(0, 3) as Vec3)
  throw new Error(`No valid coordinates found for site${idx === undefined ? `` : ` ${idx}`}`)
}

// A site's force vector, or null when it carries none. Non-finite components disqualify the
// whole vector: half a force is not a force.
const site_force = (site: Site): number[] | null => {
  const force = site.properties?.force
  if (!Array.isArray(force) || force.length < 3) return null
  const vec = force.slice(0, 3).map(Number)
  return vec.every(Number.isFinite) ? vec : null
}

// Whether any site carries per-axis motion flags. Keyed on Array.isArray, the same test
// site_move_flags reads them with, so the header and the columns can never disagree.
const has_move_flags = (structure: AnyStructure): boolean =>
  structure.sites.some((site) => Array.isArray(site.properties?.selective_dynamics))

// Per-axis motion flags, defaulting to free. Padded to exactly three so a truncated array
// can't emit a short line, which both POSCAR and extXYZ readers would mis-column.
const site_move_flags = (site: Site): [boolean, boolean, boolean] => {
  const flags = site.properties?.selective_dynamics
  const read = (axis: number) => (Array.isArray(flags) ? flags[axis] !== false : true)
  return [read(0), read(1), read(2)]
}

// Bare words in an extXYZ comment are read as valueless flags, and an `=` or `"` inside one
// would be parsed as a key/value pair, silently inventing metadata. A newline is worse still:
// it splits the comment in two, shifting every atom line and making the count line a lie.
const sanitize_comment_label = (label: string): string =>
  label.replaceAll(/["=]/g, ``).replaceAll(/\s+/g, ` `).trim()

// Generate extended XYZ content string without saving. Emits a Properties= header so the
// columns beyond `species x y z` (forces, motion constraints) survive a round trip.
export function structure_to_xyz_str(structure?: AnyStructure): string {
  if (!structure?.sites) throw new Error(`No structure or sites to export`)

  const lines: string[] = []

  // First line: number of atoms
  lines.push(String(structure.sites.length))

  // Second line: comment (structure ID, formula, or default)
  const comment_parts: string[] = []
  if (structure.id) comment_parts.push(sanitize_comment_label(structure.id))
  const formula = get_electro_neg_formula(structure, true)
  if (formula && formula !== `Unknown`) comment_parts.push(sanitize_comment_label(formula))

  const lattice_matrix =
    `lattice` in structure && structure.lattice?.matrix?.length === 3
      ? structure.lattice.matrix
      : null

  // Include extended XYZ lattice information when available so round-trips preserve lattice
  if (lattice_matrix) {
    const lattice_values = lattice_matrix
      .flatMap((row) =>
        row.map((value: number) => (Number.isFinite(value) ? value : 0).toFixed(8)),
      )
      .join(` `)
    comment_parts.push(`Lattice="${lattice_values}"`)
  }

  // Forces are all-or-nothing: padding the sites that lack one with zeros would report a
  // relaxed atom where the data simply says nothing. Constraints do have a meaningful default
  // (free to move), which is the same assumption the POSCAR exporter makes.
  const forces = structure.sites.map(site_force)
  const has_forces = forces.every((force) => force !== null) && forces.length > 0
  const has_constraints = has_move_flags(structure)

  const property_cols = [`species:S:1`, `pos:R:3`]
  if (has_forces) property_cols.push(`forces:R:3`)
  // Per-axis `move_mask:L:3`, which is what ASE itself writes for a FixCartesian constraint
  // and reads back as one. The whole-atom `move_mask:L:1` cannot express a partial `T F T`:
  // ASE collapses it to "this atom may move" and yields FixAtoms([]), i.e. no constraint.
  if (has_constraints) property_cols.push(`move_mask:L:3`)
  comment_parts.push(`Properties=${property_cols.join(`:`)}`)

  if (lattice_matrix) {
    const pbc = (`lattice` in structure && structure.lattice?.pbc) || [true, true, true]
    comment_parts.push(`pbc="${pbc.map((flag) => (flag ? `T` : `F`)).join(` `)}"`)
  }

  const comment =
    comment_parts.length > 0 ? comment_parts.join(` `) : `Generated from structure`
  lines.push(comment)

  // Cache converter for fractional→Cartesian (if lattice available)
  const frac_to_cart = lattice_matrix ? math.create_frac_to_cart(lattice_matrix) : null

  // Atom lines: element symbol followed by x, y, z coordinates
  for (const [site_idx, site] of structure.sites.entries()) {
    const element_symbol = site_element(site)

    // Prefer xyz; fall back to abc (converted to Cartesian if a lattice is available). A site
    // with neither is unexportable — writing it at the origin would look like real data.
    let coords: number[]
    if (site.xyz && Array.isArray(site.xyz) && site.xyz.length >= 3) {
      coords = site.xyz.slice(0, 3)
    } else if (site.abc?.length >= 3 && frac_to_cart) {
      coords = frac_to_cart(site.abc)
    } else throw new Error(`No valid coordinates found for site ${site_idx}`)

    // Format coordinates to reasonable precision
    const columns = coords.map((coord) => coord.toFixed(6))
    if (has_forces) columns.push(...(forces[site_idx] ?? []).map((val) => val.toFixed(6)))
    // T = free to move along that axis, matching ASE and POSCAR selective dynamics
    if (has_constraints) {
      columns.push(...site_move_flags(site).map((free) => (free ? `T` : `F`)))
    }
    lines.push(`${element_symbol} ${columns.join(` `)}`)
  }

  return lines.join(`\n`)
}

// Generate a valid CIF data block name from structure formula
// CIF block names can contain alphanumerics, underscores, but no spaces or special chars
function get_cif_block_name(structure: AnyStructure): string {
  try {
    // Count atoms per element (rounded to nearest integer for occupancy)
    const element_counts: Record<string, number> = {}
    for (const site of structure.sites) {
      if (!site.species || !Array.isArray(site.species)) continue
      for (const species of site.species) {
        if (!species.element) continue
        const count = species.occu ?? 1
        element_counts[species.element] = (element_counts[species.element] ?? 0) + count
      }
    }

    // Sort elements alphabetically and build formula string
    const elements = Object.keys(element_counts).toSorted()
    if (elements.length === 0) throw new Error(`No elements found`)

    const formula = elements
      .map((el) => {
        const count = Math.round(element_counts[el])
        if (count === 0) return null // filter out near-zero occupancies
        return count === 1 ? el : `${el}${count}`
      })
      .filter((part): part is string => part !== null)
      .join(``)

    if (!formula) throw new Error(`All occupancies round to zero`)
    return formula
  } catch {
    // Fall back to structure.id (sanitized) or generic name
    if (structure.id) {
      // Remove invalid CIF characters (keep alphanumerics and underscores)
      // and condense consecutive underscores for cleaner block names
      return structure.id.replaceAll(/[^a-zA-Z0-9_]/g, `_`).replaceAll(/_+/g, `_`)
    }
    return `structure`
  }
}

// Generate CIF content string without saving
export function structure_to_cif_str(structure?: AnyStructure): string {
  if (!structure?.sites) throw new Error(`No structure or sites to export`)
  if (!(`lattice` in structure) || !structure.lattice) {
    throw new Error(`No lattice information for CIF export`)
  }

  const lines: string[] = []

  // CIF header with data block (required by pymatgen and CIF spec)
  lines.push(`# CIF file generated by MatterViz`, `data_${get_cif_block_name(structure)}`, ``)

  // Cell parameters
  const lattice = structure.lattice
  if (lattice.a && lattice.b && lattice.c) {
    lines.push(
      `_cell_length_a ${lattice.a.toFixed(6)}`,
      `_cell_length_b ${lattice.b.toFixed(6)}`,
      `_cell_length_c ${lattice.c.toFixed(6)}`,
    )
  }
  if (lattice.alpha && lattice.beta && lattice.gamma) {
    lines.push(
      `_cell_angle_alpha ${lattice.alpha.toFixed(6)}`,
      `_cell_angle_beta ${lattice.beta.toFixed(6)}`,
      `_cell_angle_gamma ${lattice.gamma.toFixed(6)}`,
    )
  }

  // Space group information
  if (`symmetry` in structure && is_plain_object(structure.symmetry)) {
    const { space_group_number, space_group_symbol } = structure.symmetry
    if (typeof space_group_symbol === `string` && space_group_symbol) {
      // Quote H-M symbols: their spaces (e.g. 'F m -3 m') would break CIF tokenization
      lines.push(`_space_group_name_H-M_alt '${space_group_symbol}'`)
    }
    if (
      (typeof space_group_number === `number` || typeof space_group_number === `string`) &&
      space_group_number
    ) {
      lines.push(`_space_group_IT_number ${space_group_number}`)
    }
  }

  lines.push(``)

  // Explicit identity-only symmetry-ops loop (like pymatgen's CifWriter): sites are the
  // full P1 list, so without it parsers would re-apply the H-M ops and multiply sites
  lines.push(`loop_`, `_symmetry_equiv_pos_as_xyz`, `  'x, y, z'`, ``)

  // Atom site loop header
  lines.push(
    `loop_`,
    `_atom_site_label`,
    `_atom_site_type_symbol`,
    `_atom_site_fract_x`,
    `_atom_site_fract_y`,
    `_atom_site_fract_z`,
    `_atom_site_occupancy`,
  )

  // Cache inverse transpose for Cartesian→fractional conversion (avoids recomputing per site)
  const cart_to_frac =
    lattice.matrix?.length === 3 ? math.create_cart_to_frac(lattice.matrix) : null

  // Atom sites: one row per species entry so disordered (multi-species) sites
  // keep every component with its own occupancy instead of only species[0]
  for (let idx = 0; idx < structure.sites.length; idx++) {
    const site = structure.sites[idx]
    if (!site) continue // Skip if site is undefined

    const frac_coords = get_frac_coords(site, cart_to_frac, idx)
    const coords_str = frac_coords.map((coord) => coord.toFixed(8)).join(` `)

    const species_list = site.species?.length ? site.species : [{ element: `X`, occu: 1 }]
    for (const [spec_idx, species] of species_list.entries()) {
      const elem = species?.element || `X`
      // Row format: label element x y z occupancy. Labels must be unique per row,
      // so disordered sites get a per-species suffix.
      const label =
        species_list.length > 1
          ? `${elem}${idx + 1}_${spec_idx}`
          : site.label || `${elem}${idx + 1}`
      lines.push(`${label} ${elem} ${coords_str} ${(species?.occu ?? 1).toFixed(8)}`)
    }
  }

  return lines.join(`\n`)
}

// Generate VASP POSCAR content string without saving
export function structure_to_poscar_str(structure?: AnyStructure): string {
  if (!structure?.sites) throw new Error(`No structure or sites to export`)
  if (!(`lattice` in structure) || !structure.lattice) {
    throw new Error(`No lattice information for POSCAR export`)
  }
  const lines: string[] = []

  // Use plain text formula for POSCAR title to avoid HTML tags
  const formula = get_electro_neg_formula(structure, true)
  const title =
    structure.id || // oxlint-disable-line @typescript-eslint/prefer-nullish-coalescing -- first non-empty string
    (formula && formula !== `Unknown` ? formula : null) || // oxlint-disable-line @typescript-eslint/prefer-nullish-coalescing -- first non-empty string
    `Generated from structure`
  lines.push(title)
  lines.push(`1.0`) // Scale factor (1.0 for direct coordinates)

  const lattice = structure.lattice
  if (lattice.matrix && Array.isArray(lattice.matrix) && lattice.matrix.length >= 3) {
    // One line per lattice vector, exactly 3 components at 8-decimal fixed precision
    for (const vec of lattice.matrix.slice(0, 3)) {
      lines.push([vec[0], vec[1], vec[2]].map((coord) => coord.toFixed(8)).join(` `))
    }
  } else {
    throw new Error(`No valid lattice matrix for POSCAR export`)
  }

  // Group sites by element in one pass, preserving first-appearance element order
  const sites_by_element = new Map<string, Site[]>()
  for (const site of structure.sites) {
    const element_symbol = site_element(site)
    const group = sites_by_element.get(element_symbol)
    if (group) group.push(site)
    else sites_by_element.set(element_symbol, [site])
  }

  // Element symbols line
  lines.push([...sites_by_element.keys()].join(` `))

  // Atom counts line
  lines.push([...sites_by_element.values()].map((group) => group.length).join(` `))

  const has_selective_dynamics = has_move_flags(structure)
  if (has_selective_dynamics) {
    lines.push(`Selective dynamics`)
  }

  // Coordinate mode (Direct = fractional coordinates)
  lines.push(`Direct`)

  // Cache inverse transpose for Cartesian→fractional conversion (avoids recomputing per site)
  const cart_to_frac =
    lattice.matrix?.length === 3 ? math.create_cart_to_frac(lattice.matrix) : null

  // Atom coordinates grouped by element
  for (const group of sites_by_element.values()) {
    for (const site of group) {
      const frac_coords = get_frac_coords(site, cart_to_frac)
      const coords_str = frac_coords
        .slice(0, 3)
        .map((coord) => coord.toFixed(8))
        .join(` `)

      // Always three flags: a shorter selective_dynamics array would emit a truncated line
      // that VASP reads as missing constraints rather than the ones actually recorded.
      const sel_dyn_str = has_selective_dynamics
        ? ` ${site_move_flags(site)
            .map((free) => (free ? `T` : `F`))
            .join(` `)}`
        : ``

      lines.push(`${coords_str}${sel_dyn_str}`)
    }
  }

  return lines.join(`\n`)
}

// Generate JSON content string without saving
export function structure_to_json_str(structure?: AnyStructure): string {
  if (!structure) throw new Error(`No structure to export`)
  return JSON.stringify(structure, null, 2)
}

// Text export formats: serializer + file extension + MIME type per format
export const STRUCT_TEXT_FORMATS = {
  json: { to_str: structure_to_json_str, ext: `json`, mime: `application/json` },
  xyz: { to_str: structure_to_xyz_str, ext: `xyz`, mime: `text/plain` },
  cif: { to_str: structure_to_cif_str, ext: `cif`, mime: `chemical/x-cif` },
  poscar: { to_str: structure_to_poscar_str, ext: `poscar`, mime: `text/plain` },
} as const

export type StructTextFormat = keyof typeof STRUCT_TEXT_FORMATS

// Serialize structure in the given text format and trigger a browser download
export function export_structure_as(fmt: StructTextFormat, structure?: AnyStructure): void {
  const { to_str, ext, mime } = STRUCT_TEXT_FORMATS[fmt]
  try {
    const content = to_str(structure)
    download(content, create_structure_filename(structure, ext), mime)
  } catch (error) {
    console.error(`Failed to export ${fmt.toUpperCase()}:`, error)
  }
}

// Export Three.js scene as GLB (binary GLTF) file
// GLB preserves materials and colors, making it ideal for element visualization
export function export_structure_as_glb(
  scene: Scene | null,
  structure: AnyStructure | undefined,
): void {
  try {
    if (!scene) {
      console.warn(`No scene available for GLB export`)
      return
    }

    // Convert instanced meshes to regular meshes for export
    const export_scene = convert_instanced_meshes_to_regular(scene)

    const exporter = new GLTFExporter()
    const filename = create_structure_filename(structure, `glb`)

    // Export as binary GLB format
    exporter.parse(
      export_scene,
      (result) => {
        if (result instanceof ArrayBuffer) {
          const blob = new Blob([result], { type: `model/gltf-binary` })
          download(blob, filename, `model/gltf-binary`)
        } else {
          console.error(`GLB export returned unexpected format`)
        }
      },
      (error) => {
        console.error(`GLB export failed:`, error)
      },
      { binary: true },
    )
  } catch (error) {
    console.error(`Error exporting GLB:`, error)
  }
}

// Export Three.js scene as OBJ (Wavefront Object) file with accompanying MTL file for materials
// OBJ exports geometry with material references, MTL contains color definitions
export function export_structure_as_obj(
  scene: Scene | null,
  structure: AnyStructure | undefined,
): void {
  try {
    if (!scene) {
      console.warn(`No scene available for OBJ export`)
      return
    }

    // Convert instanced meshes to regular meshes for export
    const export_scene = convert_instanced_meshes_to_regular(scene)

    const obj_exporter = new OBJExporter()

    const base_filename = create_structure_filename(structure, ``).replace(/\.$/, ``)
    const obj_filename = `${base_filename}.obj`
    const mtl_filename = `${base_filename}.mtl`

    // Generate OBJ content with material library reference
    let obj_content = obj_exporter.parse(export_scene)
    // Add material library reference at the beginning of the OBJ file
    obj_content = `mtllib ${mtl_filename}\n${obj_content}`

    // Generate MTL content with material color definitions
    const mtl_content = generate_mtl_content(export_scene)

    // Download both files
    const obj_blob = new Blob([obj_content], { type: `text/plain` })
    const mtl_blob = new Blob([mtl_content], { type: `text/plain` })

    download(obj_blob, obj_filename, `text/plain`)
    // Small delay to prevent some browsers from blocking rapid successive downloads as potential abuse.
    // A more robust solution might be to zip both files together.
    setTimeout(() => download(mtl_blob, mtl_filename, `text/plain`), 100)
  } catch (error) {
    console.error(`Error exporting OBJ:`, error)
  }
}
