import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { gunzipSync } from 'node:zlib'

const root_dir = resolve(import.meta.dirname, `..`)
const gz_path = resolve(root_dir, `src/lib/element/data.json.gz`)
const out_dir = resolve(root_dir, `dist/element`)
const out_path = resolve(out_dir, `data.js`)

mkdirSync(out_dir, { recursive: true })
const json = JSON.parse(gunzipSync(readFileSync(gz_path)).toString(`utf8`))
writeFileSync(
  out_path,
  `// Generated by scripts/package-dist-assets.ts
const element_data = ${JSON.stringify(json)};
export const element_by_symbol = new Map(
  element_data.map((element) => [element.symbol, element]),
);
export default element_data;
`,
)
