import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gunzipSync } from 'node:zlib'

const root_dir = resolve(dirname(fileURLToPath(import.meta.url)), `..`)
const gz_path = resolve(root_dir, `src/lib/element/data.json.gz`)
const out_dir = resolve(root_dir, `dist/element`)
const out_path = resolve(out_dir, `data.js`)

mkdirSync(out_dir, { recursive: true })
const json = JSON.parse(gunzipSync(readFileSync(gz_path)).toString(`utf8`))
writeFileSync(
  out_path,
  `// Generated by scripts/package-dist-assets.ts\nexport default ${JSON.stringify(json)};\n`,
)
