# AUTO-GENERATED by scripts/sync_typed_wrappers.py
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Any

from .MatterViz import MatterViz

class Structure(MatterViz):
    """3D crystal structure / molecule viewer.

    Underlying MatterViz component key: ``structure/Structure``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_file_drop

    Not supported in Dash
    --------------------
    Snippet/slot props are omitted from this wrapper:
        top_right_controls

    Prop reference (TypeScript)
    ---------------------------
    - allow_file_drop -> allow_file_drop: boolean
    - atom_color_config -> atom_color_config: Partial<AtomColorConfig>
    - cell_type -> cell_type: CellType
    - data_url -> data_url: string
    - displayed_structure -> displayed_structure: AnyStructure
    - dragover -> dragover: boolean
    - element_mapping -> element_mapping: Partial<Record<ElementSymbol, ElementSymbol>>
    - enable_info_pane -> enable_info_pane: boolean
    - enable_measure_mode -> enable_measure_mode: boolean
    - error_msg -> error_msg: string
    - fullscreen -> fullscreen: boolean
    - height -> height: number
    - hidden_elements -> hidden_elements: Set<ElementSymbol>
    - hidden_prop_vals -> hidden_prop_vals: Set<number | string>
    - hovered -> hovered: boolean
    - info_pane_open -> info_pane_open: boolean
    - loading -> loading: boolean
    - measured_sites -> measured_sites: number[]
    - on_camera_move -> on_camera_move: EventHandler
    - on_camera_reset -> on_camera_reset: EventHandler
    - on_error -> on_error: EventHandler
    - on_file_load -> on_file_load: EventHandler
    - on_fullscreen_change -> on_fullscreen_change: EventHandler
    - performance_mode -> performance_mode: `quality` | `speed`
    - png_dpi -> png_dpi: number
    - reset_text -> reset_text: string
    - scene_props -> scene_props: ComponentProps<typeof StructureScene>
    - selected_sites -> selected_sites: number[]
    - show_controls -> show_controls: boolean | number
    - spinner_props -> spinner_props: ComponentProps<typeof Spinner>
    - structure -> structure: AnyStructure
    - structure_string -> structure_string: string
    - sym_data -> sym_data: MoyoDataset | null
    - symmetry_settings -> symmetry_settings: Partial<SymmetrySettings>
    - width -> width: number
    """

    def __init__(self, id=None, allow_file_drop: bool | None = None, atom_color_config: dict | None = None, cell_type: Any | None = None, data_url: str | None = None, displayed_structure: Any | None = None, dragover: bool | None = None, element_mapping: dict | None = None, enable_info_pane: bool | None = None, enable_measure_mode: bool | None = None, error_msg: str | None = None, fullscreen: bool | None = None, height: float | None = None, hidden_elements: list | None = None, hidden_prop_vals: list | None = None, hovered: bool | None = None, info_pane_open: bool | None = None, loading: bool | None = None, measured_sites: list[float] | None = None, on_camera_move: Any | None = None, on_camera_reset: Any | None = None, on_error: Any | None = None, on_file_load: Any | None = None, on_fullscreen_change: Any | None = None, performance_mode: Any | None = None, png_dpi: float | None = None, reset_text: str | None = None, scene_props: dict | None = None, selected_sites: list[float] | None = None, show_controls: bool | None = None, spinner_props: dict | None = None, structure: Any | None = None, structure_string: str | None = None, sym_data: Any | None = None, symmetry_settings: dict | None = None, width: float | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if allow_file_drop is not None:
            _mv['allow_file_drop'] = allow_file_drop
        if atom_color_config is not None:
            _mv['atom_color_config'] = atom_color_config
        if cell_type is not None:
            _mv['cell_type'] = cell_type
        if data_url is not None:
            _mv['data_url'] = data_url
        if displayed_structure is not None:
            _mv['displayed_structure'] = displayed_structure
        if dragover is not None:
            _mv['dragover'] = dragover
        if element_mapping is not None:
            _mv['element_mapping'] = element_mapping
        if enable_info_pane is not None:
            _mv['enable_info_pane'] = enable_info_pane
        if enable_measure_mode is not None:
            _mv['enable_measure_mode'] = enable_measure_mode
        if error_msg is not None:
            _mv['error_msg'] = error_msg
        if fullscreen is not None:
            _mv['fullscreen'] = fullscreen
        if height is not None:
            _mv['height'] = height
        if hidden_elements is not None:
            _mv['hidden_elements'] = hidden_elements
        if hidden_prop_vals is not None:
            _mv['hidden_prop_vals'] = hidden_prop_vals
        if hovered is not None:
            _mv['hovered'] = hovered
        if info_pane_open is not None:
            _mv['info_pane_open'] = info_pane_open
        if loading is not None:
            _mv['loading'] = loading
        if measured_sites is not None:
            _mv['measured_sites'] = measured_sites
        if on_camera_move is not None:
            _mv['on_camera_move'] = on_camera_move
        if on_camera_reset is not None:
            _mv['on_camera_reset'] = on_camera_reset
        if on_error is not None:
            _mv['on_error'] = on_error
        if on_file_load is not None:
            _mv['on_file_load'] = on_file_load
        if on_fullscreen_change is not None:
            _mv['on_fullscreen_change'] = on_fullscreen_change
        if performance_mode is not None:
            _mv['performance_mode'] = performance_mode
        if png_dpi is not None:
            _mv['png_dpi'] = png_dpi
        if reset_text is not None:
            _mv['reset_text'] = reset_text
        if scene_props is not None:
            _mv['scene_props'] = scene_props
        if selected_sites is not None:
            _mv['selected_sites'] = selected_sites
        if show_controls is not None:
            _mv['show_controls'] = show_controls
        if spinner_props is not None:
            _mv['spinner_props'] = spinner_props
        if structure is not None:
            _mv['structure'] = structure
        if structure_string is not None:
            _mv['structure_string'] = structure_string
        if sym_data is not None:
            _mv['sym_data'] = sym_data
        if symmetry_settings is not None:
            _mv['symmetry_settings'] = symmetry_settings
        if width is not None:
            _mv['width'] = width
        if mv_props:
            _mv.update(mv_props)

        if set_props is None:
            set_props = ['hidden_elements', 'hidden_prop_vals']

        super().__init__(
            id=id,
            component='structure/Structure',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class PeriodicTable(MatterViz):
    """Interactive periodic table with heatmaps and tooltips.

    Underlying MatterViz component key: ``periodic-table/PeriodicTable``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        color_scale, onenter

    Not supported in Dash
    --------------------
    Snippet/slot props are omitted from this wrapper:
        children

    Prop reference (TypeScript)
    ---------------------------
    - active_category -> active_category: ElementCategory | null
    - active_element -> active_element: ChemicalElement | null
    - active_elements -> active_elements: (ElementSymbol | ChemicalElement)[]
    - color_bar_props -> color_bar_props: Partial<ComponentProps<typeof ColorBar>>
    - color_overrides -> color_overrides: Partial<Record<ElementSymbol, string>>
    - color_scale_range -> color_scale_range: [number | null, number | null]
    - disabled -> disabled: boolean
    - gap -> gap: string
    - heatmap_values -> heatmap_values: Partial<Record<ElementSymbol, number | number[] | string | string[]>> | (number | number[] | string | string[])[]
    - inner_transition_metal_offset -> inner_transition_metal_offset: number
    - labels -> labels: Partial<Record<ElementSymbol, string>>
    - lanth_act_style -> lanth_act_style: string
    - links -> links: keyof ChemicalElement | Record<ElementSymbol, string> | null
    - log -> log: boolean
    - missing_color -> missing_color: string
    - show_color_bar -> show_color_bar: boolean
    - show_photo -> show_photo: boolean
    - split_layout -> split_layout: `diagonal` | `horizontal` | `vertical` | `triangular` | `quadrant`
    - tile_props -> tile_props: Partial<ComponentProps<typeof ElementTile>>
    """

    def __init__(self, id=None, active_category: Any | None = None, active_element: Any | None = None, active_elements: list | None = None, color_bar_props: dict | None = None, color_overrides: dict | None = None, color_scale_range: list | None = None, disabled: bool | None = None, gap: str | None = None, heatmap_values: list[dict] | None = None, inner_transition_metal_offset: float | None = None, labels: dict | None = None, lanth_act_style: str | None = None, links: dict | None = None, log: bool | None = None, missing_color: str | None = None, show_color_bar: bool | None = None, show_photo: bool | None = None, split_layout: Any | None = None, tile_props: dict | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if active_category is not None:
            _mv['active_category'] = active_category
        if active_element is not None:
            _mv['active_element'] = active_element
        if active_elements is not None:
            _mv['active_elements'] = active_elements
        if color_bar_props is not None:
            _mv['color_bar_props'] = color_bar_props
        if color_overrides is not None:
            _mv['color_overrides'] = color_overrides
        if color_scale_range is not None:
            _mv['color_scale_range'] = color_scale_range
        if disabled is not None:
            _mv['disabled'] = disabled
        if gap is not None:
            _mv['gap'] = gap
        if heatmap_values is not None:
            _mv['heatmap_values'] = heatmap_values
        if inner_transition_metal_offset is not None:
            _mv['inner_transition_metal_offset'] = inner_transition_metal_offset
        if labels is not None:
            _mv['labels'] = labels
        if lanth_act_style is not None:
            _mv['lanth_act_style'] = lanth_act_style
        if links is not None:
            _mv['links'] = links
        if log is not None:
            _mv['log'] = log
        if missing_color is not None:
            _mv['missing_color'] = missing_color
        if show_color_bar is not None:
            _mv['show_color_bar'] = show_color_bar
        if show_photo is not None:
            _mv['show_photo'] = show_photo
        if split_layout is not None:
            _mv['split_layout'] = split_layout
        if tile_props is not None:
            _mv['tile_props'] = tile_props
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='periodic-table/PeriodicTable',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Composition(MatterViz):
    """Composition chart (pie/bubble/bar) for a chemical formula or composition dict.

    Underlying MatterViz component key: ``composition/Composition``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_composition_change

    Prop reference (TypeScript)
    ---------------------------
    - color_scheme -> color_scheme: ColorSchemeName
    - composition -> composition: string | CompositionType (required in TS)
    - interactive -> interactive: boolean
    - mode -> mode: CompositionChartMode
    - size -> size: number
    """

    def __init__(self, id=None, color_scheme: Any | None = None, composition: str | None = None, interactive: bool | None = None, mode: Any | None = None, size: float | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if color_scheme is not None:
            _mv['color_scheme'] = color_scheme
        if composition is not None:
            _mv['composition'] = composition
        if interactive is not None:
            _mv['interactive'] = interactive
        if mode is not None:
            _mv['mode'] = mode
        if size is not None:
            _mv['size'] = size
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='composition/Composition',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Trajectory(MatterViz):
    """Molecular dynamics trajectory viewer with structure + plots.

    Underlying MatterViz component key: ``trajectory/Trajectory``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_display_mode_change, on_end, on_error, on_file_load, on_frame_rate_change, on_fullscreen_change, on_loop, on_pause, on_play, on_step_change

    Not supported in Dash
    --------------------
    Snippet/slot props are omitted from this wrapper:
        trajectory_controls

    Prop reference (TypeScript)
    ---------------------------
    - elem_property_labels -> ELEM_PROPERTY_LABELS: Record<string, string>
    - allow_file_drop -> allow_file_drop: boolean
    - atom_type_mapping -> atom_type_mapping: AtomTypeMapping
    - auto_play -> auto_play: boolean
    - current_step_idx -> current_step_idx: number
    - data_extractor -> data_extractor: TrajectoryDataExtractor
    - data_url -> data_url: string
    - display_mode -> display_mode: `structure+scatter` | `structure` | `scatter` | `histogram` | `structure+histogram`
    - fps -> fps: number
    - fps_range -> fps_range: [number, number]
    - histogram_props -> histogram_props: Omit<ComponentProps<typeof Histogram>, `series`>
    - layout -> layout: `auto` | Orientation
    - loading_options -> loading_options: LoadingOptions
    - plot_skimming -> plot_skimming: boolean
    - scatter_props -> scatter_props: ComponentProps<typeof ScatterPlot>
    - show_controls -> show_controls: boolean
    - spinner_props -> spinner_props: ComponentProps<typeof Spinner>
    - step_labels -> step_labels: number | number[]
    - structure_props -> structure_props: ComponentProps<typeof Structure>
    - trajectory -> trajectory: TrajectoryType
    - visible_properties -> visible_properties: string[]
    """

    def __init__(self, id=None, elem_property_labels: dict | None = None, allow_file_drop: bool | None = None, atom_type_mapping: Any | None = None, auto_play: bool | None = None, current_step_idx: float | None = None, data_extractor: Any | None = None, data_url: str | None = None, display_mode: Any | None = None, fps: float | None = None, fps_range: list | None = None, histogram_props: dict | None = None, layout: Any | None = None, loading_options: Any | None = None, plot_skimming: bool | None = None, scatter_props: dict | None = None, show_controls: bool | None = None, spinner_props: dict | None = None, step_labels: list[float] | None = None, structure_props: dict | None = None, trajectory: Any | None = None, visible_properties: list[str] | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if elem_property_labels is not None:
            _mv['ELEM_PROPERTY_LABELS'] = elem_property_labels
        if allow_file_drop is not None:
            _mv['allow_file_drop'] = allow_file_drop
        if atom_type_mapping is not None:
            _mv['atom_type_mapping'] = atom_type_mapping
        if auto_play is not None:
            _mv['auto_play'] = auto_play
        if current_step_idx is not None:
            _mv['current_step_idx'] = current_step_idx
        if data_extractor is not None:
            _mv['data_extractor'] = data_extractor
        if data_url is not None:
            _mv['data_url'] = data_url
        if display_mode is not None:
            _mv['display_mode'] = display_mode
        if fps is not None:
            _mv['fps'] = fps
        if fps_range is not None:
            _mv['fps_range'] = fps_range
        if histogram_props is not None:
            _mv['histogram_props'] = histogram_props
        if layout is not None:
            _mv['layout'] = layout
        if loading_options is not None:
            _mv['loading_options'] = loading_options
        if plot_skimming is not None:
            _mv['plot_skimming'] = plot_skimming
        if scatter_props is not None:
            _mv['scatter_props'] = scatter_props
        if show_controls is not None:
            _mv['show_controls'] = show_controls
        if spinner_props is not None:
            _mv['spinner_props'] = spinner_props
        if step_labels is not None:
            _mv['step_labels'] = step_labels
        if structure_props is not None:
            _mv['structure_props'] = structure_props
        if trajectory is not None:
            _mv['trajectory'] = trajectory
        if visible_properties is not None:
            _mv['visible_properties'] = visible_properties
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='trajectory/Trajectory',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class BrillouinZone(MatterViz):
    """3D Brillouin zone visualization.

    Underlying MatterViz component key: ``brillouin/BrillouinZone``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_error, on_file_drop, on_file_load, on_fullscreen_change

    Prop reference (TypeScript)
    ---------------------------
    - allow_file_drop -> allow_file_drop: boolean
    - bz_data -> bz_data: BrillouinZoneData
    - bz_order -> bz_order: number
    - camera_projection -> camera_projection: CameraProjection
    - controls_open -> controls_open: boolean
    - data_url -> data_url: string
    - dragover -> dragover: boolean
    - edge_color -> edge_color: string
    - edge_width -> edge_width: number
    - error_msg -> error_msg: string
    - fullscreen -> fullscreen: boolean
    - height -> height: number
    - hovered -> hovered: boolean
    - hovered_k_point -> hovered_k_point: Vec3 | null
    - hovered_qpoint_index -> hovered_qpoint_index: number | null
    - info_pane_open -> info_pane_open: boolean
    - k_path_points -> k_path_points: Vec3[]
    - loading -> loading: boolean
    - png_dpi -> png_dpi: number
    - show_controls -> show_controls: boolean | number
    - show_vectors -> show_vectors: boolean
    - spinner_props -> spinner_props: ComponentProps<typeof Spinner>
    - structure -> structure: Crystal
    - structure_string -> structure_string: string
    - surface_color -> surface_color: string
    - surface_opacity -> surface_opacity: number
    - vector_scale -> vector_scale: number
    - width -> width: number
    """

    def __init__(self, id=None, allow_file_drop: bool | None = None, bz_data: Any | None = None, bz_order: float | None = None, camera_projection: Any | None = None, controls_open: bool | None = None, data_url: str | None = None, dragover: bool | None = None, edge_color: str | None = None, edge_width: float | None = None, error_msg: str | None = None, fullscreen: bool | None = None, height: float | None = None, hovered: bool | None = None, hovered_k_point: Any | None = None, hovered_qpoint_index: float | None = None, info_pane_open: bool | None = None, k_path_points: list | None = None, loading: bool | None = None, png_dpi: float | None = None, show_controls: bool | None = None, show_vectors: bool | None = None, spinner_props: dict | None = None, structure: Any | None = None, structure_string: str | None = None, surface_color: str | None = None, surface_opacity: float | None = None, vector_scale: float | None = None, width: float | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if allow_file_drop is not None:
            _mv['allow_file_drop'] = allow_file_drop
        if bz_data is not None:
            _mv['bz_data'] = bz_data
        if bz_order is not None:
            _mv['bz_order'] = bz_order
        if camera_projection is not None:
            _mv['camera_projection'] = camera_projection
        if controls_open is not None:
            _mv['controls_open'] = controls_open
        if data_url is not None:
            _mv['data_url'] = data_url
        if dragover is not None:
            _mv['dragover'] = dragover
        if edge_color is not None:
            _mv['edge_color'] = edge_color
        if edge_width is not None:
            _mv['edge_width'] = edge_width
        if error_msg is not None:
            _mv['error_msg'] = error_msg
        if fullscreen is not None:
            _mv['fullscreen'] = fullscreen
        if height is not None:
            _mv['height'] = height
        if hovered is not None:
            _mv['hovered'] = hovered
        if hovered_k_point is not None:
            _mv['hovered_k_point'] = hovered_k_point
        if hovered_qpoint_index is not None:
            _mv['hovered_qpoint_index'] = hovered_qpoint_index
        if info_pane_open is not None:
            _mv['info_pane_open'] = info_pane_open
        if k_path_points is not None:
            _mv['k_path_points'] = k_path_points
        if loading is not None:
            _mv['loading'] = loading
        if png_dpi is not None:
            _mv['png_dpi'] = png_dpi
        if show_controls is not None:
            _mv['show_controls'] = show_controls
        if show_vectors is not None:
            _mv['show_vectors'] = show_vectors
        if spinner_props is not None:
            _mv['spinner_props'] = spinner_props
        if structure is not None:
            _mv['structure'] = structure
        if structure_string is not None:
            _mv['structure_string'] = structure_string
        if surface_color is not None:
            _mv['surface_color'] = surface_color
        if surface_opacity is not None:
            _mv['surface_opacity'] = surface_opacity
        if vector_scale is not None:
            _mv['vector_scale'] = vector_scale
        if width is not None:
            _mv['width'] = width
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='brillouin/BrillouinZone',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class ConvexHull2D(MatterViz):
    """2D convex hull phase diagram plot.

    Underlying MatterViz component key: ``convex-hull/ConvexHull2D``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_point_click, on_point_hover, on_file_drop

    Not supported in Dash
    --------------------
    Snippet/slot props are omitted from this wrapper:
        children

    Prop reference (TypeScript)
    ---------------------------
    - highlight_style -> highlight_style: HighlightStyle
    - x_axis -> x_axis: AxisConfig
    - y_axis -> y_axis: AxisConfig
    - entries -> entries: PhaseData[] (required in TS)
    - controls -> controls: Partial<ConvexHullControlsType>
    - config -> config: Partial<ConvexHullConfig>
    - fullscreen -> fullscreen: boolean
    - enable_fullscreen -> enable_fullscreen: boolean
    - enable_info_pane -> enable_info_pane: boolean
    - label_threshold -> label_threshold: number
    - show_stable -> show_stable: boolean
    - show_unstable -> show_unstable: boolean
    - color_mode -> color_mode: `stability` | `energy`
    - color_scale -> color_scale: D3InterpolateName
    - info_pane_open -> info_pane_open: boolean
    - legend_pane_open -> legend_pane_open: boolean
    - max_hull_dist_show_phases -> max_hull_dist_show_phases: number
    - max_hull_dist_show_labels -> max_hull_dist_show_labels: number
    - show_stable_labels -> show_stable_labels: boolean
    - show_unstable_labels -> show_unstable_labels: boolean
    - enable_click_selection -> enable_click_selection: boolean
    - enable_structure_preview -> enable_structure_preview: boolean
    - energy_source_mode -> energy_source_mode: `precomputed` | `on-the-fly`
    - phase_stats -> phase_stats: PhaseStats | null
    - stable_entries -> stable_entries: AnyDimEntry[]
    - unstable_entries -> unstable_entries: AnyDimEntry[]
    - highlighted_entries -> highlighted_entries: (string | AnyDimEntry)[]
    - selected_entry -> selected_entry: AnyDimEntry | null
    """

    def __init__(self, id=None, highlight_style: Any | None = None, x_axis: Any | None = None, y_axis: Any | None = None, entries: list | None = None, controls: dict | None = None, config: dict | None = None, fullscreen: bool | None = None, enable_fullscreen: bool | None = None, enable_info_pane: bool | None = None, label_threshold: float | None = None, show_stable: bool | None = None, show_unstable: bool | None = None, color_mode: Any | None = None, color_scale: Any | None = None, info_pane_open: bool | None = None, legend_pane_open: bool | None = None, max_hull_dist_show_phases: float | None = None, max_hull_dist_show_labels: float | None = None, show_stable_labels: bool | None = None, show_unstable_labels: bool | None = None, enable_click_selection: bool | None = None, enable_structure_preview: bool | None = None, energy_source_mode: Any | None = None, phase_stats: Any | None = None, stable_entries: list | None = None, unstable_entries: list | None = None, highlighted_entries: list | None = None, selected_entry: Any | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if highlight_style is not None:
            _mv['highlight_style'] = highlight_style
        if x_axis is not None:
            _mv['x_axis'] = x_axis
        if y_axis is not None:
            _mv['y_axis'] = y_axis
        if entries is not None:
            _mv['entries'] = entries
        if controls is not None:
            _mv['controls'] = controls
        if config is not None:
            _mv['config'] = config
        if fullscreen is not None:
            _mv['fullscreen'] = fullscreen
        if enable_fullscreen is not None:
            _mv['enable_fullscreen'] = enable_fullscreen
        if enable_info_pane is not None:
            _mv['enable_info_pane'] = enable_info_pane
        if label_threshold is not None:
            _mv['label_threshold'] = label_threshold
        if show_stable is not None:
            _mv['show_stable'] = show_stable
        if show_unstable is not None:
            _mv['show_unstable'] = show_unstable
        if color_mode is not None:
            _mv['color_mode'] = color_mode
        if color_scale is not None:
            _mv['color_scale'] = color_scale
        if info_pane_open is not None:
            _mv['info_pane_open'] = info_pane_open
        if legend_pane_open is not None:
            _mv['legend_pane_open'] = legend_pane_open
        if max_hull_dist_show_phases is not None:
            _mv['max_hull_dist_show_phases'] = max_hull_dist_show_phases
        if max_hull_dist_show_labels is not None:
            _mv['max_hull_dist_show_labels'] = max_hull_dist_show_labels
        if show_stable_labels is not None:
            _mv['show_stable_labels'] = show_stable_labels
        if show_unstable_labels is not None:
            _mv['show_unstable_labels'] = show_unstable_labels
        if enable_click_selection is not None:
            _mv['enable_click_selection'] = enable_click_selection
        if enable_structure_preview is not None:
            _mv['enable_structure_preview'] = enable_structure_preview
        if energy_source_mode is not None:
            _mv['energy_source_mode'] = energy_source_mode
        if phase_stats is not None:
            _mv['phase_stats'] = phase_stats
        if stable_entries is not None:
            _mv['stable_entries'] = stable_entries
        if unstable_entries is not None:
            _mv['unstable_entries'] = unstable_entries
        if highlighted_entries is not None:
            _mv['highlighted_entries'] = highlighted_entries
        if selected_entry is not None:
            _mv['selected_entry'] = selected_entry
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='convex-hull/ConvexHull2D',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class ConvexHull3D(MatterViz):
    """3D convex hull phase diagram plot.

    Underlying MatterViz component key: ``convex-hull/ConvexHull3D``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_point_click, on_point_hover, on_file_drop

    Not supported in Dash
    --------------------
    Snippet/slot props are omitted from this wrapper:
        children

    Prop reference (TypeScript)
    ---------------------------
    - highlight_style -> highlight_style: HighlightStyle
    - entries -> entries: PhaseData[] (required in TS)
    - controls -> controls: Partial<ConvexHullControlsType>
    - config -> config: Partial<ConvexHullConfig>
    - fullscreen -> fullscreen: boolean
    - enable_fullscreen -> enable_fullscreen: boolean
    - enable_info_pane -> enable_info_pane: boolean
    - label_threshold -> label_threshold: number
    - show_stable -> show_stable: boolean
    - show_unstable -> show_unstable: boolean
    - color_mode -> color_mode: `stability` | `energy`
    - color_scale -> color_scale: D3InterpolateName
    - info_pane_open -> info_pane_open: boolean
    - legend_pane_open -> legend_pane_open: boolean
    - max_hull_dist_show_phases -> max_hull_dist_show_phases: number
    - max_hull_dist_show_labels -> max_hull_dist_show_labels: number
    - show_stable_labels -> show_stable_labels: boolean
    - show_unstable_labels -> show_unstable_labels: boolean
    - enable_click_selection -> enable_click_selection: boolean
    - enable_structure_preview -> enable_structure_preview: boolean
    - energy_source_mode -> energy_source_mode: `precomputed` | `on-the-fly`
    - phase_stats -> phase_stats: PhaseStats | null
    - stable_entries -> stable_entries: AnyDimEntry[]
    - unstable_entries -> unstable_entries: AnyDimEntry[]
    - highlighted_entries -> highlighted_entries: (string | AnyDimEntry)[]
    - selected_entry -> selected_entry: AnyDimEntry | null
    - show_hull_faces -> show_hull_faces: boolean
    - hull_face_opacity -> hull_face_opacity: number
    """

    def __init__(self, id=None, highlight_style: Any | None = None, entries: list | None = None, controls: dict | None = None, config: dict | None = None, fullscreen: bool | None = None, enable_fullscreen: bool | None = None, enable_info_pane: bool | None = None, label_threshold: float | None = None, show_stable: bool | None = None, show_unstable: bool | None = None, color_mode: Any | None = None, color_scale: Any | None = None, info_pane_open: bool | None = None, legend_pane_open: bool | None = None, max_hull_dist_show_phases: float | None = None, max_hull_dist_show_labels: float | None = None, show_stable_labels: bool | None = None, show_unstable_labels: bool | None = None, enable_click_selection: bool | None = None, enable_structure_preview: bool | None = None, energy_source_mode: Any | None = None, phase_stats: Any | None = None, stable_entries: list | None = None, unstable_entries: list | None = None, highlighted_entries: list | None = None, selected_entry: Any | None = None, show_hull_faces: bool | None = None, hull_face_opacity: float | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if highlight_style is not None:
            _mv['highlight_style'] = highlight_style
        if entries is not None:
            _mv['entries'] = entries
        if controls is not None:
            _mv['controls'] = controls
        if config is not None:
            _mv['config'] = config
        if fullscreen is not None:
            _mv['fullscreen'] = fullscreen
        if enable_fullscreen is not None:
            _mv['enable_fullscreen'] = enable_fullscreen
        if enable_info_pane is not None:
            _mv['enable_info_pane'] = enable_info_pane
        if label_threshold is not None:
            _mv['label_threshold'] = label_threshold
        if show_stable is not None:
            _mv['show_stable'] = show_stable
        if show_unstable is not None:
            _mv['show_unstable'] = show_unstable
        if color_mode is not None:
            _mv['color_mode'] = color_mode
        if color_scale is not None:
            _mv['color_scale'] = color_scale
        if info_pane_open is not None:
            _mv['info_pane_open'] = info_pane_open
        if legend_pane_open is not None:
            _mv['legend_pane_open'] = legend_pane_open
        if max_hull_dist_show_phases is not None:
            _mv['max_hull_dist_show_phases'] = max_hull_dist_show_phases
        if max_hull_dist_show_labels is not None:
            _mv['max_hull_dist_show_labels'] = max_hull_dist_show_labels
        if show_stable_labels is not None:
            _mv['show_stable_labels'] = show_stable_labels
        if show_unstable_labels is not None:
            _mv['show_unstable_labels'] = show_unstable_labels
        if enable_click_selection is not None:
            _mv['enable_click_selection'] = enable_click_selection
        if enable_structure_preview is not None:
            _mv['enable_structure_preview'] = enable_structure_preview
        if energy_source_mode is not None:
            _mv['energy_source_mode'] = energy_source_mode
        if phase_stats is not None:
            _mv['phase_stats'] = phase_stats
        if stable_entries is not None:
            _mv['stable_entries'] = stable_entries
        if unstable_entries is not None:
            _mv['unstable_entries'] = unstable_entries
        if highlighted_entries is not None:
            _mv['highlighted_entries'] = highlighted_entries
        if selected_entry is not None:
            _mv['selected_entry'] = selected_entry
        if show_hull_faces is not None:
            _mv['show_hull_faces'] = show_hull_faces
        if hull_face_opacity is not None:
            _mv['hull_face_opacity'] = hull_face_opacity
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='convex-hull/ConvexHull3D',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class ConvexHull4D(MatterViz):
    """4D convex hull phase diagram plot (for quaternary systems).

    Underlying MatterViz component key: ``convex-hull/ConvexHull4D``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_point_click, on_point_hover, on_file_drop

    Not supported in Dash
    --------------------
    Snippet/slot props are omitted from this wrapper:
        children

    Prop reference (TypeScript)
    ---------------------------
    - highlight_style -> highlight_style: HighlightStyle
    - entries -> entries: PhaseData[] (required in TS)
    - controls -> controls: Partial<ConvexHullControlsType>
    - config -> config: Partial<ConvexHullConfig>
    - fullscreen -> fullscreen: boolean
    - enable_fullscreen -> enable_fullscreen: boolean
    - enable_info_pane -> enable_info_pane: boolean
    - label_threshold -> label_threshold: number
    - show_stable -> show_stable: boolean
    - show_unstable -> show_unstable: boolean
    - color_mode -> color_mode: `stability` | `energy`
    - color_scale -> color_scale: D3InterpolateName
    - info_pane_open -> info_pane_open: boolean
    - legend_pane_open -> legend_pane_open: boolean
    - max_hull_dist_show_phases -> max_hull_dist_show_phases: number
    - max_hull_dist_show_labels -> max_hull_dist_show_labels: number
    - show_stable_labels -> show_stable_labels: boolean
    - show_unstable_labels -> show_unstable_labels: boolean
    - enable_click_selection -> enable_click_selection: boolean
    - enable_structure_preview -> enable_structure_preview: boolean
    - energy_source_mode -> energy_source_mode: `precomputed` | `on-the-fly`
    - phase_stats -> phase_stats: PhaseStats | null
    - stable_entries -> stable_entries: AnyDimEntry[]
    - unstable_entries -> unstable_entries: AnyDimEntry[]
    - highlighted_entries -> highlighted_entries: (string | AnyDimEntry)[]
    - selected_entry -> selected_entry: AnyDimEntry | null
    - show_hull_faces -> show_hull_faces: boolean
    - hull_face_opacity -> hull_face_opacity: number
    """

    def __init__(self, id=None, highlight_style: Any | None = None, entries: list | None = None, controls: dict | None = None, config: dict | None = None, fullscreen: bool | None = None, enable_fullscreen: bool | None = None, enable_info_pane: bool | None = None, label_threshold: float | None = None, show_stable: bool | None = None, show_unstable: bool | None = None, color_mode: Any | None = None, color_scale: Any | None = None, info_pane_open: bool | None = None, legend_pane_open: bool | None = None, max_hull_dist_show_phases: float | None = None, max_hull_dist_show_labels: float | None = None, show_stable_labels: bool | None = None, show_unstable_labels: bool | None = None, enable_click_selection: bool | None = None, enable_structure_preview: bool | None = None, energy_source_mode: Any | None = None, phase_stats: Any | None = None, stable_entries: list | None = None, unstable_entries: list | None = None, highlighted_entries: list | None = None, selected_entry: Any | None = None, show_hull_faces: bool | None = None, hull_face_opacity: float | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if highlight_style is not None:
            _mv['highlight_style'] = highlight_style
        if entries is not None:
            _mv['entries'] = entries
        if controls is not None:
            _mv['controls'] = controls
        if config is not None:
            _mv['config'] = config
        if fullscreen is not None:
            _mv['fullscreen'] = fullscreen
        if enable_fullscreen is not None:
            _mv['enable_fullscreen'] = enable_fullscreen
        if enable_info_pane is not None:
            _mv['enable_info_pane'] = enable_info_pane
        if label_threshold is not None:
            _mv['label_threshold'] = label_threshold
        if show_stable is not None:
            _mv['show_stable'] = show_stable
        if show_unstable is not None:
            _mv['show_unstable'] = show_unstable
        if color_mode is not None:
            _mv['color_mode'] = color_mode
        if color_scale is not None:
            _mv['color_scale'] = color_scale
        if info_pane_open is not None:
            _mv['info_pane_open'] = info_pane_open
        if legend_pane_open is not None:
            _mv['legend_pane_open'] = legend_pane_open
        if max_hull_dist_show_phases is not None:
            _mv['max_hull_dist_show_phases'] = max_hull_dist_show_phases
        if max_hull_dist_show_labels is not None:
            _mv['max_hull_dist_show_labels'] = max_hull_dist_show_labels
        if show_stable_labels is not None:
            _mv['show_stable_labels'] = show_stable_labels
        if show_unstable_labels is not None:
            _mv['show_unstable_labels'] = show_unstable_labels
        if enable_click_selection is not None:
            _mv['enable_click_selection'] = enable_click_selection
        if enable_structure_preview is not None:
            _mv['enable_structure_preview'] = enable_structure_preview
        if energy_source_mode is not None:
            _mv['energy_source_mode'] = energy_source_mode
        if phase_stats is not None:
            _mv['phase_stats'] = phase_stats
        if stable_entries is not None:
            _mv['stable_entries'] = stable_entries
        if unstable_entries is not None:
            _mv['unstable_entries'] = unstable_entries
        if highlighted_entries is not None:
            _mv['highlighted_entries'] = highlighted_entries
        if selected_entry is not None:
            _mv['selected_entry'] = selected_entry
        if show_hull_faces is not None:
            _mv['show_hull_faces'] = show_hull_faces
        if hull_face_opacity is not None:
            _mv['hull_face_opacity'] = hull_face_opacity
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='convex-hull/ConvexHull4D',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class IsobaricBinaryPhaseDiagram(MatterViz):
    """Binary isobaric phase diagram.

    Underlying MatterViz component key: ``phase-diagram/IsobaricBinaryPhaseDiagram``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_phase_hover

    Not supported in Dash
    --------------------
    Snippet/slot props are omitted from this wrapper:
        tooltip

    Prop reference (TypeScript)
    ---------------------------
    - config -> config: Partial<PhaseDiagramConfig>
    - controls_open -> controls_open: boolean
    - controls_props -> controls_props: Partial<ComponentProps<typeof PhaseDiagramControls>>
    - data -> data: PhaseDiagramData (required in TS)
    - display_temp_unit -> display_temp_unit: `K` | `°C` | `°F`
    - enable_export -> enable_export: boolean
    - export_filename -> export_filename: string
    - export_pane_open -> export_pane_open: boolean
    - fullscreen -> fullscreen: boolean
    - fullscreen_toggle -> fullscreen_toggle: boolean
    - hovered_region -> hovered_region: PhaseRegion | null
    - png_dpi -> png_dpi: number
    - show_boundaries -> show_boundaries: boolean
    - show_component_labels -> show_component_labels: boolean
    - show_controls -> show_controls: boolean
    - show_grid -> show_grid: boolean
    - show_labels -> show_labels: boolean
    - show_special_points -> show_special_points: boolean
    - x_axis -> x_axis: AxisConfig
    - y_axis -> y_axis: AxisConfig
    """

    def __init__(self, id=None, config: dict | None = None, controls_open: bool | None = None, controls_props: dict | None = None, data: Any | None = None, display_temp_unit: Any | None = None, enable_export: bool | None = None, export_filename: str | None = None, export_pane_open: bool | None = None, fullscreen: bool | None = None, fullscreen_toggle: bool | None = None, hovered_region: Any | None = None, png_dpi: float | None = None, show_boundaries: bool | None = None, show_component_labels: bool | None = None, show_controls: bool | None = None, show_grid: bool | None = None, show_labels: bool | None = None, show_special_points: bool | None = None, x_axis: Any | None = None, y_axis: Any | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if config is not None:
            _mv['config'] = config
        if controls_open is not None:
            _mv['controls_open'] = controls_open
        if controls_props is not None:
            _mv['controls_props'] = controls_props
        if data is not None:
            _mv['data'] = data
        if display_temp_unit is not None:
            _mv['display_temp_unit'] = display_temp_unit
        if enable_export is not None:
            _mv['enable_export'] = enable_export
        if export_filename is not None:
            _mv['export_filename'] = export_filename
        if export_pane_open is not None:
            _mv['export_pane_open'] = export_pane_open
        if fullscreen is not None:
            _mv['fullscreen'] = fullscreen
        if fullscreen_toggle is not None:
            _mv['fullscreen_toggle'] = fullscreen_toggle
        if hovered_region is not None:
            _mv['hovered_region'] = hovered_region
        if png_dpi is not None:
            _mv['png_dpi'] = png_dpi
        if show_boundaries is not None:
            _mv['show_boundaries'] = show_boundaries
        if show_component_labels is not None:
            _mv['show_component_labels'] = show_component_labels
        if show_controls is not None:
            _mv['show_controls'] = show_controls
        if show_grid is not None:
            _mv['show_grid'] = show_grid
        if show_labels is not None:
            _mv['show_labels'] = show_labels
        if show_special_points is not None:
            _mv['show_special_points'] = show_special_points
        if x_axis is not None:
            _mv['x_axis'] = x_axis
        if y_axis is not None:
            _mv['y_axis'] = y_axis
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='phase-diagram/IsobaricBinaryPhaseDiagram',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class IsobaricTernaryPhaseDiagram(MatterViz):
    """Ternary isobaric phase diagram.

    Underlying MatterViz component key: ``phase-diagram/IsobaricTernaryPhaseDiagram``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_region_hover

    Not supported in Dash
    --------------------
    Snippet/slot props are omitted from this wrapper:
        tooltip

    Prop reference (TypeScript)
    ---------------------------
    - auto_rotate -> auto_rotate: number
    - camera -> camera: Camera
    - camera_position -> camera_position: Vec3
    - config -> config: Partial<TernaryPhaseDiagramConfig>
    - controls_open -> controls_open: boolean
    - data -> data: TernaryPhaseDiagramData (required in TS)
    - enable_export -> enable_export: boolean
    - export_filename -> export_filename: string
    - export_pane_open -> export_pane_open: boolean
    - fullscreen -> fullscreen: boolean
    - fullscreen_toggle -> fullscreen_toggle: boolean
    - hovered_region -> hovered_region: TernaryPhaseRegion | null
    - orbit_controls -> orbit_controls: ComponentProps<typeof extras.OrbitControls>[`ref`]
    - png_dpi -> png_dpi: number
    - region_opacity -> region_opacity: number
    - render_mode -> render_mode: `transparent` | `solid`
    - scene -> scene: Scene
    - show_boundaries -> show_boundaries: boolean
    - show_controls -> show_controls: boolean
    - show_grid -> show_grid: boolean
    - show_isothermal_panel -> show_isothermal_panel: boolean
    - show_labels -> show_labels: boolean
    - show_special_points -> show_special_points: boolean
    - show_vertical_panel -> show_vertical_panel: boolean
    - slice_ratio -> slice_ratio: number
    - slice_temperature -> slice_temperature: number
    """

    def __init__(self, id=None, auto_rotate: float | None = None, camera: Any | None = None, camera_position: Any | None = None, config: dict | None = None, controls_open: bool | None = None, data: Any | None = None, enable_export: bool | None = None, export_filename: str | None = None, export_pane_open: bool | None = None, fullscreen: bool | None = None, fullscreen_toggle: bool | None = None, hovered_region: Any | None = None, orbit_controls: dict | None = None, png_dpi: float | None = None, region_opacity: float | None = None, render_mode: Any | None = None, scene: Any | None = None, show_boundaries: bool | None = None, show_controls: bool | None = None, show_grid: bool | None = None, show_isothermal_panel: bool | None = None, show_labels: bool | None = None, show_special_points: bool | None = None, show_vertical_panel: bool | None = None, slice_ratio: float | None = None, slice_temperature: float | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if auto_rotate is not None:
            _mv['auto_rotate'] = auto_rotate
        if camera is not None:
            _mv['camera'] = camera
        if camera_position is not None:
            _mv['camera_position'] = camera_position
        if config is not None:
            _mv['config'] = config
        if controls_open is not None:
            _mv['controls_open'] = controls_open
        if data is not None:
            _mv['data'] = data
        if enable_export is not None:
            _mv['enable_export'] = enable_export
        if export_filename is not None:
            _mv['export_filename'] = export_filename
        if export_pane_open is not None:
            _mv['export_pane_open'] = export_pane_open
        if fullscreen is not None:
            _mv['fullscreen'] = fullscreen
        if fullscreen_toggle is not None:
            _mv['fullscreen_toggle'] = fullscreen_toggle
        if hovered_region is not None:
            _mv['hovered_region'] = hovered_region
        if orbit_controls is not None:
            _mv['orbit_controls'] = orbit_controls
        if png_dpi is not None:
            _mv['png_dpi'] = png_dpi
        if region_opacity is not None:
            _mv['region_opacity'] = region_opacity
        if render_mode is not None:
            _mv['render_mode'] = render_mode
        if scene is not None:
            _mv['scene'] = scene
        if show_boundaries is not None:
            _mv['show_boundaries'] = show_boundaries
        if show_controls is not None:
            _mv['show_controls'] = show_controls
        if show_grid is not None:
            _mv['show_grid'] = show_grid
        if show_isothermal_panel is not None:
            _mv['show_isothermal_panel'] = show_isothermal_panel
        if show_labels is not None:
            _mv['show_labels'] = show_labels
        if show_special_points is not None:
            _mv['show_special_points'] = show_special_points
        if show_vertical_panel is not None:
            _mv['show_vertical_panel'] = show_vertical_panel
        if slice_ratio is not None:
            _mv['slice_ratio'] = slice_ratio
        if slice_temperature is not None:
            _mv['slice_temperature'] = slice_temperature
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='phase-diagram/IsobaricTernaryPhaseDiagram',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class XrdPlot(MatterViz):
    """X-ray diffraction pattern plot.

    Underlying MatterViz component key: ``xrd/XrdPlot``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_file_drop

    Prop reference (TypeScript)
    ---------------------------
    - allow_file_drop -> allow_file_drop: boolean
    - annotate_peaks -> annotate_peaks: number
    - broadening_enabled -> broadening_enabled: boolean
    - broadening_params -> broadening_params: BroadeningParams
    - controls -> controls: ControlsConfig
    - error_msg -> error_msg: string
    - hkl_format -> hkl_format: HklFormat
    - loading -> loading: boolean
    - peak_width -> peak_width: number
    - show_angles -> show_angles: boolean | null
    - wavelength -> wavelength: number | null
    - x_axis -> x_axis: AxisConfig
    - y_axis -> y_axis: AxisConfig
    - patterns -> patterns: XrdPattern | Record<string, XrdPattern | { pattern: XrdPattern; color?: string }> | PatternEntry[] (required in TS)
    """

    def __init__(self, id=None, allow_file_drop: bool | None = None, annotate_peaks: float | None = None, broadening_enabled: bool | None = None, broadening_params: Any | None = None, controls: Any | None = None, error_msg: str | None = None, hkl_format: Any | None = None, loading: bool | None = None, peak_width: float | None = None, show_angles: bool | None = None, wavelength: float | None = None, x_axis: Any | None = None, y_axis: Any | None = None, patterns: list[dict] | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if allow_file_drop is not None:
            _mv['allow_file_drop'] = allow_file_drop
        if annotate_peaks is not None:
            _mv['annotate_peaks'] = annotate_peaks
        if broadening_enabled is not None:
            _mv['broadening_enabled'] = broadening_enabled
        if broadening_params is not None:
            _mv['broadening_params'] = broadening_params
        if controls is not None:
            _mv['controls'] = controls
        if error_msg is not None:
            _mv['error_msg'] = error_msg
        if hkl_format is not None:
            _mv['hkl_format'] = hkl_format
        if loading is not None:
            _mv['loading'] = loading
        if peak_width is not None:
            _mv['peak_width'] = peak_width
        if show_angles is not None:
            _mv['show_angles'] = show_angles
        if wavelength is not None:
            _mv['wavelength'] = wavelength
        if x_axis is not None:
            _mv['x_axis'] = x_axis
        if y_axis is not None:
            _mv['y_axis'] = y_axis
        if patterns is not None:
            _mv['patterns'] = patterns
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='xrd/XrdPlot',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Bands(MatterViz):
    """Band structure dispersion plot (phonon or electronic).

    Underlying MatterViz component key: ``spectral/Bands``.

    Prop reference (TypeScript)
    ---------------------------
    - band_structs -> band_structs: BaseBandStructure | Record<string, BaseBandStructure> (required in TS)
    - band_type -> band_type: BandStructureType
    - fermi_level -> fermi_level: number
    - line_kwargs -> line_kwargs: LineKwargs
    - path_mode -> path_mode: PathMode
    - reference_frequency -> reference_frequency: number | null
    - ribbon_config -> ribbon_config: RibbonConfig | Record<string, RibbonConfig>
    - show_legend -> show_legend: boolean
    - x_axis -> x_axis: AxisConfig
    - x_positions -> x_positions: Record<string, [number, number]>
    - y_axis -> y_axis: AxisConfig
    """

    def __init__(self, id=None, band_structs: dict | None = None, band_type: Any | None = None, fermi_level: float | None = None, line_kwargs: Any | None = None, path_mode: Any | None = None, reference_frequency: float | None = None, ribbon_config: dict | None = None, show_legend: bool | None = None, x_axis: Any | None = None, x_positions: dict | None = None, y_axis: Any | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if band_structs is not None:
            _mv['band_structs'] = band_structs
        if band_type is not None:
            _mv['band_type'] = band_type
        if fermi_level is not None:
            _mv['fermi_level'] = fermi_level
        if line_kwargs is not None:
            _mv['line_kwargs'] = line_kwargs
        if path_mode is not None:
            _mv['path_mode'] = path_mode
        if reference_frequency is not None:
            _mv['reference_frequency'] = reference_frequency
        if ribbon_config is not None:
            _mv['ribbon_config'] = ribbon_config
        if show_legend is not None:
            _mv['show_legend'] = show_legend
        if x_axis is not None:
            _mv['x_axis'] = x_axis
        if x_positions is not None:
            _mv['x_positions'] = x_positions
        if y_axis is not None:
            _mv['y_axis'] = y_axis
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='spectral/Bands',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Dos(MatterViz):
    """Density of states plot (electronic or phonon).

    Underlying MatterViz component key: ``spectral/Dos``.

    Prop reference (TypeScript)
    ---------------------------
    - doses -> doses: DosInput | Record<string, DosInput> (required in TS)
    - fermi_level -> fermi_level: number
    - hovered_frequency -> hovered_frequency: number | null
    - normalize -> normalize: NormalizationMode
    - orientation -> orientation: `vertical` | `horizontal`
    - reference_frequency -> reference_frequency: number | null
    - show_legend -> show_legend: boolean
    - sigma -> sigma: number
    - stack -> stack: boolean
    - units -> units: FrequencyUnit
    - x_axis -> x_axis: AxisConfig
    - y_axis -> y_axis: AxisConfig
    """

    def __init__(self, id=None, doses: dict | None = None, fermi_level: float | None = None, hovered_frequency: float | None = None, normalize: Any | None = None, orientation: Any | None = None, reference_frequency: float | None = None, show_legend: bool | None = None, sigma: float | None = None, stack: bool | None = None, units: Any | None = None, x_axis: Any | None = None, y_axis: Any | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if doses is not None:
            _mv['doses'] = doses
        if fermi_level is not None:
            _mv['fermi_level'] = fermi_level
        if hovered_frequency is not None:
            _mv['hovered_frequency'] = hovered_frequency
        if normalize is not None:
            _mv['normalize'] = normalize
        if orientation is not None:
            _mv['orientation'] = orientation
        if reference_frequency is not None:
            _mv['reference_frequency'] = reference_frequency
        if show_legend is not None:
            _mv['show_legend'] = show_legend
        if sigma is not None:
            _mv['sigma'] = sigma
        if stack is not None:
            _mv['stack'] = stack
        if units is not None:
            _mv['units'] = units
        if x_axis is not None:
            _mv['x_axis'] = x_axis
        if y_axis is not None:
            _mv['y_axis'] = y_axis
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='spectral/Dos',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class ScatterPlot(MatterViz):
    """General-purpose scatter plot with customizable axes and tooltips.

    Underlying MatterViz component key: ``plot/ScatterPlot``.

    Prop reference (TypeScript)
    ---------------------------
    """

    def __init__(self, id=None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='plot/ScatterPlot',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Histogram(MatterViz):
    """Histogram plot for data distributions.

    Underlying MatterViz component key: ``plot/Histogram``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_series_toggle

    Not supported in Dash
    --------------------
    Snippet/slot props are omitted from this wrapper:
        controls_extra, tooltip

    Prop reference (TypeScript)
    ---------------------------
    - bar -> bar: BarStyle
    - bins -> bins: number
    - legend -> legend: LegendConfig | null
    - mode -> mode: `single` | `overlay`
    - selected_property -> selected_property: string
    - series -> series: DataSeries[] (required in TS)
    - show_legend -> show_legend: boolean
    """

    def __init__(self, id=None, bar: Any | None = None, bins: float | None = None, legend: Any | None = None, mode: Any | None = None, selected_property: str | None = None, series: list | None = None, show_legend: bool | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if bar is not None:
            _mv['bar'] = bar
        if bins is not None:
            _mv['bins'] = bins
        if legend is not None:
            _mv['legend'] = legend
        if mode is not None:
            _mv['mode'] = mode
        if selected_property is not None:
            _mv['selected_property'] = selected_property
        if series is not None:
            _mv['series'] = series
        if show_legend is not None:
            _mv['show_legend'] = show_legend
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='plot/Histogram',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class RdfPlot(MatterViz):
    """Radial distribution function (RDF) plot.

    Underlying MatterViz component key: ``rdf/RdfPlot``.

    Events
    ------
    MatterViz exposes callback props (functions) as events via ``event_props``.
    For this component, available callback props include:
        on_file_drop

    Prop reference (TypeScript)
    ---------------------------
    - cutoff -> cutoff: number
    - drag_dropped -> drag_dropped: Crystal[]
    - dragging -> dragging: boolean
    - enable_drop -> enable_drop: boolean
    - error_msg -> error_msg: string
    - loading -> loading: boolean
    - mode -> mode: `element_pairs` | `full`
    - n_bins -> n_bins: number
    - patterns -> patterns: RdfEntry | RdfEntry[]
    - pbc -> pbc: Pbc
    - show_reference_line -> show_reference_line: boolean
    - structures -> structures: Crystal | Crystal[] | Record<string, Crystal>
    - x_axis -> x_axis: ComponentProps<typeof ScatterPlot>[`x_axis`]
    - y_axis -> y_axis: ComponentProps<typeof ScatterPlot>[`y_axis`]
    """

    def __init__(self, id=None, cutoff: float | None = None, drag_dropped: list | None = None, dragging: bool | None = None, enable_drop: bool | None = None, error_msg: str | None = None, loading: bool | None = None, mode: Any | None = None, n_bins: float | None = None, patterns: list | None = None, pbc: Any | None = None, show_reference_line: bool | None = None, structures: dict | None = None, x_axis: dict | None = None, y_axis: dict | None = None, mv_props: dict | None = None, set_props: list[str] | None = None, float32_props: list[str] | None = None, event_props: list[str] | None = None, last_event: dict | None = None, className: str | None = None, style: dict | None = None, **kwargs):
        _mv: dict = {}
        if cutoff is not None:
            _mv['cutoff'] = cutoff
        if drag_dropped is not None:
            _mv['drag_dropped'] = drag_dropped
        if dragging is not None:
            _mv['dragging'] = dragging
        if enable_drop is not None:
            _mv['enable_drop'] = enable_drop
        if error_msg is not None:
            _mv['error_msg'] = error_msg
        if loading is not None:
            _mv['loading'] = loading
        if mode is not None:
            _mv['mode'] = mode
        if n_bins is not None:
            _mv['n_bins'] = n_bins
        if patterns is not None:
            _mv['patterns'] = patterns
        if pbc is not None:
            _mv['pbc'] = pbc
        if show_reference_line is not None:
            _mv['show_reference_line'] = show_reference_line
        if structures is not None:
            _mv['structures'] = structures
        if x_axis is not None:
            _mv['x_axis'] = x_axis
        if y_axis is not None:
            _mv['y_axis'] = y_axis
        if mv_props:
            _mv.update(mv_props)


        super().__init__(
            id=id,
            component='rdf/RdfPlot',
            mv_props=_mv,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )
