# AUTO-GENERATED by scripts/sync_typed_wrappers.py - DO NOT EDIT
#
# Type Inference: number -> float (int if prop contains _idx/_index/_count/etc.)
# Override via manifest [components.Name.type_hints] = { prop = 'int' }

from __future__ import annotations

from typing import Any

from .MatterViz import MatterViz

class Structure(MatterViz):
    """3D crystal structure / molecule viewer.

    Component key: ``structure/Structure``

    Events: on_file_drop

    Unsupported snippets: top_right_controls
    """

    def __init__(
        self,
        id=None,
        allow_file_drop: bool | None = None,
        atom_color_config: dict | None = None,
        cell_type: Any | None = None,
        data_url: str | None = None,
        displayed_structure: Any | None = None,
        dragover: bool | None = None,
        element_mapping: dict | None = None,
        element_radius_overrides: dict | None = None,
        enable_info_pane: bool | None = None,
        enable_measure_mode: bool | None = None,
        error_msg: str | None = None,
        fullscreen: bool | None = None,
        height: float | None = None,
        hidden_elements: list | None = None,
        hidden_prop_vals: list | None = None,
        hovered: bool | None = None,
        info_pane_open: bool | None = None,
        loading: bool | None = None,
        measured_sites: list[int] | None = None,
        on_camera_move: Any | None = None,
        on_camera_reset: Any | None = None,
        on_error: Any | None = None,
        on_file_load: Any | None = None,
        on_fullscreen_change: Any | None = None,
        performance_mode: Any | None = None,
        png_dpi: float | None = None,
        reset_text: str | None = None,
        scene_props: dict | None = None,
        selected_sites: list[int] | None = None,
        site_radius_overrides: Any | None = None,
        spinner_props: dict | None = None,
        structure: Any | None = None,
        structure_string: str | None = None,
        sym_data: Any | None = None,
        symmetry_settings: dict | None = None,
        width: float | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if allow_file_drop is not None:
            mv_props["allow_file_drop"] = allow_file_drop
        if atom_color_config is not None:
            mv_props["atom_color_config"] = atom_color_config
        if cell_type is not None:
            mv_props["cell_type"] = cell_type
        if data_url is not None:
            mv_props["data_url"] = data_url
        if displayed_structure is not None:
            mv_props["displayed_structure"] = displayed_structure
        if dragover is not None:
            mv_props["dragover"] = dragover
        if element_mapping is not None:
            mv_props["element_mapping"] = element_mapping
        if element_radius_overrides is not None:
            mv_props["element_radius_overrides"] = element_radius_overrides
        if enable_info_pane is not None:
            mv_props["enable_info_pane"] = enable_info_pane
        if enable_measure_mode is not None:
            mv_props["enable_measure_mode"] = enable_measure_mode
        if error_msg is not None:
            mv_props["error_msg"] = error_msg
        if fullscreen is not None:
            mv_props["fullscreen"] = fullscreen
        if height is not None:
            mv_props["height"] = height
        if hidden_elements is not None:
            mv_props["hidden_elements"] = hidden_elements
        if hidden_prop_vals is not None:
            mv_props["hidden_prop_vals"] = hidden_prop_vals
        if hovered is not None:
            mv_props["hovered"] = hovered
        if info_pane_open is not None:
            mv_props["info_pane_open"] = info_pane_open
        if loading is not None:
            mv_props["loading"] = loading
        if measured_sites is not None:
            mv_props["measured_sites"] = measured_sites
        if on_camera_move is not None:
            mv_props["on_camera_move"] = on_camera_move
        if on_camera_reset is not None:
            mv_props["on_camera_reset"] = on_camera_reset
        if on_error is not None:
            mv_props["on_error"] = on_error
        if on_file_load is not None:
            mv_props["on_file_load"] = on_file_load
        if on_fullscreen_change is not None:
            mv_props["on_fullscreen_change"] = on_fullscreen_change
        if performance_mode is not None:
            mv_props["performance_mode"] = performance_mode
        if png_dpi is not None:
            mv_props["png_dpi"] = png_dpi
        if reset_text is not None:
            mv_props["reset_text"] = reset_text
        if scene_props is not None:
            mv_props["scene_props"] = scene_props
        if selected_sites is not None:
            mv_props["selected_sites"] = selected_sites
        if site_radius_overrides is not None:
            mv_props["site_radius_overrides"] = site_radius_overrides
        if spinner_props is not None:
            mv_props["spinner_props"] = spinner_props
        if structure is not None:
            mv_props["structure"] = structure
        if structure_string is not None:
            mv_props["structure_string"] = structure_string
        if sym_data is not None:
            mv_props["sym_data"] = sym_data
        if symmetry_settings is not None:
            mv_props["symmetry_settings"] = symmetry_settings
        if width is not None:
            mv_props["width"] = width
        if set_props is None:
            set_props = ["hidden_elements", "hidden_prop_vals"]

        super().__init__(
            id=id,
            component="structure/Structure",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class PeriodicTable(MatterViz):
    """Interactive periodic table with heatmaps and tooltips.

    Component key: ``periodic-table/PeriodicTable``

    Events: color_scale, onenter

    Unsupported snippets: children
    """

    def __init__(
        self,
        id=None,
        active_category: Any | None = None,
        active_element: Any | None = None,
        active_elements: list | None = None,
        color_bar_props: dict | None = None,
        color_overrides: dict | None = None,
        color_scale_range: list | None = None,
        disabled: bool | None = None,
        gap: str | None = None,
        heatmap_values: list[dict] | None = None,
        inner_transition_metal_offset: float | None = None,
        labels: dict | None = None,
        lanth_act_style: str | None = None,
        links: dict | None = None,
        log: bool | None = None,
        missing_color: str | None = None,
        show_color_bar: bool | None = None,
        show_photo: bool | None = None,
        split_layout: Any | None = None,
        tile_props: dict | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if active_category is not None:
            mv_props["active_category"] = active_category
        if active_element is not None:
            mv_props["active_element"] = active_element
        if active_elements is not None:
            mv_props["active_elements"] = active_elements
        if color_bar_props is not None:
            mv_props["color_bar_props"] = color_bar_props
        if color_overrides is not None:
            mv_props["color_overrides"] = color_overrides
        if color_scale_range is not None:
            mv_props["color_scale_range"] = color_scale_range
        if disabled is not None:
            mv_props["disabled"] = disabled
        if gap is not None:
            mv_props["gap"] = gap
        if heatmap_values is not None:
            mv_props["heatmap_values"] = heatmap_values
        if inner_transition_metal_offset is not None:
            mv_props["inner_transition_metal_offset"] = inner_transition_metal_offset
        if labels is not None:
            mv_props["labels"] = labels
        if lanth_act_style is not None:
            mv_props["lanth_act_style"] = lanth_act_style
        if links is not None:
            mv_props["links"] = links
        if log is not None:
            mv_props["log"] = log
        if missing_color is not None:
            mv_props["missing_color"] = missing_color
        if show_color_bar is not None:
            mv_props["show_color_bar"] = show_color_bar
        if show_photo is not None:
            mv_props["show_photo"] = show_photo
        if split_layout is not None:
            mv_props["split_layout"] = split_layout
        if tile_props is not None:
            mv_props["tile_props"] = tile_props

        super().__init__(
            id=id,
            component="periodic-table/PeriodicTable",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Composition(MatterViz):
    """Composition chart (pie/bubble/bar) for a chemical formula or composition dict.

    Component key: ``composition/Composition``

    Events: on_composition_change
    """

    def __init__(
        self,
        id=None,
        color_scheme: Any | None = None,
        composition: str | None = None,
        interactive: bool | None = None,
        mode: Any | None = None,
        size: float | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if color_scheme is not None:
            mv_props["color_scheme"] = color_scheme
        if composition is not None:
            mv_props["composition"] = composition
        if interactive is not None:
            mv_props["interactive"] = interactive
        if mode is not None:
            mv_props["mode"] = mode
        if size is not None:
            mv_props["size"] = size

        super().__init__(
            id=id,
            component="composition/Composition",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Trajectory(MatterViz):
    """Molecular dynamics trajectory viewer with structure + plots.

    Component key: ``trajectory/Trajectory``

    Events: on_display_mode_change, on_end, on_error, on_file_load, on_frame_rate_change, on_fullscreen_change, on_loop, on_pause, on_play, on_step_change

    Unsupported snippets: trajectory_controls
    """

    def __init__(
        self,
        id=None,
        elem_property_labels: dict | None = None,
        allow_file_drop: bool | None = None,
        atom_type_mapping: Any | None = None,
        auto_play: bool | None = None,
        current_step_idx: int | None = None,
        data_extractor: Any | None = None,
        data_url: str | None = None,
        display_mode: Any | None = None,
        fps: float | None = None,
        fps_range: list | None = None,
        histogram_props: dict | None = None,
        layout: Any | None = None,
        loading_options: Any | None = None,
        plot_skimming: bool | None = None,
        scatter_props: dict | None = None,
        show_controls: Any | None = None,
        spinner_props: dict | None = None,
        step_labels: list[float] | None = None,
        structure_props: dict | None = None,
        trajectory: Any | None = None,
        visible_properties: list[str] | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if elem_property_labels is not None:
            mv_props["ELEM_PROPERTY_LABELS"] = elem_property_labels
        if allow_file_drop is not None:
            mv_props["allow_file_drop"] = allow_file_drop
        if atom_type_mapping is not None:
            mv_props["atom_type_mapping"] = atom_type_mapping
        if auto_play is not None:
            mv_props["auto_play"] = auto_play
        if current_step_idx is not None:
            mv_props["current_step_idx"] = current_step_idx
        if data_extractor is not None:
            mv_props["data_extractor"] = data_extractor
        if data_url is not None:
            mv_props["data_url"] = data_url
        if display_mode is not None:
            mv_props["display_mode"] = display_mode
        if fps is not None:
            mv_props["fps"] = fps
        if fps_range is not None:
            mv_props["fps_range"] = fps_range
        if histogram_props is not None:
            mv_props["histogram_props"] = histogram_props
        if layout is not None:
            mv_props["layout"] = layout
        if loading_options is not None:
            mv_props["loading_options"] = loading_options
        if plot_skimming is not None:
            mv_props["plot_skimming"] = plot_skimming
        if scatter_props is not None:
            mv_props["scatter_props"] = scatter_props
        if show_controls is not None:
            mv_props["show_controls"] = show_controls
        if spinner_props is not None:
            mv_props["spinner_props"] = spinner_props
        if step_labels is not None:
            mv_props["step_labels"] = step_labels
        if structure_props is not None:
            mv_props["structure_props"] = structure_props
        if trajectory is not None:
            mv_props["trajectory"] = trajectory
        if visible_properties is not None:
            mv_props["visible_properties"] = visible_properties

        super().__init__(
            id=id,
            component="trajectory/Trajectory",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class BrillouinZone(MatterViz):
    """3D Brillouin zone visualization.

    Component key: ``brillouin/BrillouinZone``

    Events: on_error, on_file_drop, on_file_load, on_fullscreen_change, on_hover
    """

    def __init__(
        self,
        id=None,
        allow_file_drop: bool | None = None,
        bz_data: Any | None = None,
        bz_order: float | None = None,
        camera_projection: Any | None = None,
        controls_open: bool | None = None,
        data_url: str | None = None,
        dragover: bool | None = None,
        edge_color: str | None = None,
        edge_width: float | None = None,
        error_msg: str | None = None,
        fullscreen: bool | None = None,
        height: float | None = None,
        hovered: bool | None = None,
        hovered_k_point: Any | None = None,
        hovered_qpoint_index: int | None = None,
        ibz_color: str | None = None,
        ibz_data: Any | None = None,
        ibz_opacity: float | None = None,
        info_pane_open: bool | None = None,
        k_path_points: list | None = None,
        loading: bool | None = None,
        png_dpi: float | None = None,
        show_ibz: bool | None = None,
        show_vectors: bool | None = None,
        spinner_props: dict | None = None,
        structure: Any | None = None,
        structure_string: str | None = None,
        surface_color: str | None = None,
        surface_opacity: float | None = None,
        tooltip_config: Any | None = None,
        vector_scale: float | None = None,
        width: float | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if allow_file_drop is not None:
            mv_props["allow_file_drop"] = allow_file_drop
        if bz_data is not None:
            mv_props["bz_data"] = bz_data
        if bz_order is not None:
            mv_props["bz_order"] = bz_order
        if camera_projection is not None:
            mv_props["camera_projection"] = camera_projection
        if controls_open is not None:
            mv_props["controls_open"] = controls_open
        if data_url is not None:
            mv_props["data_url"] = data_url
        if dragover is not None:
            mv_props["dragover"] = dragover
        if edge_color is not None:
            mv_props["edge_color"] = edge_color
        if edge_width is not None:
            mv_props["edge_width"] = edge_width
        if error_msg is not None:
            mv_props["error_msg"] = error_msg
        if fullscreen is not None:
            mv_props["fullscreen"] = fullscreen
        if height is not None:
            mv_props["height"] = height
        if hovered is not None:
            mv_props["hovered"] = hovered
        if hovered_k_point is not None:
            mv_props["hovered_k_point"] = hovered_k_point
        if hovered_qpoint_index is not None:
            mv_props["hovered_qpoint_index"] = hovered_qpoint_index
        if ibz_color is not None:
            mv_props["ibz_color"] = ibz_color
        if ibz_data is not None:
            mv_props["ibz_data"] = ibz_data
        if ibz_opacity is not None:
            mv_props["ibz_opacity"] = ibz_opacity
        if info_pane_open is not None:
            mv_props["info_pane_open"] = info_pane_open
        if k_path_points is not None:
            mv_props["k_path_points"] = k_path_points
        if loading is not None:
            mv_props["loading"] = loading
        if png_dpi is not None:
            mv_props["png_dpi"] = png_dpi
        if show_ibz is not None:
            mv_props["show_ibz"] = show_ibz
        if show_vectors is not None:
            mv_props["show_vectors"] = show_vectors
        if spinner_props is not None:
            mv_props["spinner_props"] = spinner_props
        if structure is not None:
            mv_props["structure"] = structure
        if structure_string is not None:
            mv_props["structure_string"] = structure_string
        if surface_color is not None:
            mv_props["surface_color"] = surface_color
        if surface_opacity is not None:
            mv_props["surface_opacity"] = surface_opacity
        if tooltip_config is not None:
            mv_props["tooltip_config"] = tooltip_config
        if vector_scale is not None:
            mv_props["vector_scale"] = vector_scale
        if width is not None:
            mv_props["width"] = width

        super().__init__(
            id=id,
            component="brillouin/BrillouinZone",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class ConvexHull2D(MatterViz):
    """2D convex hull phase diagram plot.

    Component key: ``convex-hull/ConvexHull2D``

    Events: on_point_click, on_point_hover, on_file_drop

    Unsupported snippets: children
    """

    def __init__(
        self,
        id=None,
        highlight_style: Any | None = None,
        x_axis: Any | None = None,
        y_axis: Any | None = None,
        entries: list | None = None,
        controls: dict | None = None,
        config: dict | None = None,
        fullscreen: bool | None = None,
        enable_fullscreen: bool | None = None,
        enable_info_pane: bool | None = None,
        label_threshold: float | None = None,
        show_stable: bool | None = None,
        show_unstable: bool | None = None,
        color_mode: Any | None = None,
        color_scale: Any | None = None,
        info_pane_open: bool | None = None,
        legend_pane_open: bool | None = None,
        max_hull_dist_show_phases: float | None = None,
        max_hull_dist_show_labels: float | None = None,
        show_stable_labels: bool | None = None,
        show_unstable_labels: bool | None = None,
        enable_click_selection: bool | None = None,
        enable_structure_preview: bool | None = None,
        energy_source_mode: Any | None = None,
        phase_stats: Any | None = None,
        stable_entries: list | None = None,
        unstable_entries: list | None = None,
        highlighted_entries: list | None = None,
        selected_entry: Any | None = None,
        tooltip: Any | None = None,
        temperature: float | None = None,
        interpolate_temperature: bool | None = None,
        max_interpolation_gap: float | None = None,
        gas_config: Any | None = None,
        gas_pressures: dict | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if highlight_style is not None:
            mv_props["highlight_style"] = highlight_style
        if x_axis is not None:
            mv_props["x_axis"] = x_axis
        if y_axis is not None:
            mv_props["y_axis"] = y_axis
        if entries is not None:
            mv_props["entries"] = entries
        if controls is not None:
            mv_props["controls"] = controls
        if config is not None:
            mv_props["config"] = config
        if fullscreen is not None:
            mv_props["fullscreen"] = fullscreen
        if enable_fullscreen is not None:
            mv_props["enable_fullscreen"] = enable_fullscreen
        if enable_info_pane is not None:
            mv_props["enable_info_pane"] = enable_info_pane
        if label_threshold is not None:
            mv_props["label_threshold"] = label_threshold
        if show_stable is not None:
            mv_props["show_stable"] = show_stable
        if show_unstable is not None:
            mv_props["show_unstable"] = show_unstable
        if color_mode is not None:
            mv_props["color_mode"] = color_mode
        if color_scale is not None:
            mv_props["color_scale"] = color_scale
        if info_pane_open is not None:
            mv_props["info_pane_open"] = info_pane_open
        if legend_pane_open is not None:
            mv_props["legend_pane_open"] = legend_pane_open
        if max_hull_dist_show_phases is not None:
            mv_props["max_hull_dist_show_phases"] = max_hull_dist_show_phases
        if max_hull_dist_show_labels is not None:
            mv_props["max_hull_dist_show_labels"] = max_hull_dist_show_labels
        if show_stable_labels is not None:
            mv_props["show_stable_labels"] = show_stable_labels
        if show_unstable_labels is not None:
            mv_props["show_unstable_labels"] = show_unstable_labels
        if enable_click_selection is not None:
            mv_props["enable_click_selection"] = enable_click_selection
        if enable_structure_preview is not None:
            mv_props["enable_structure_preview"] = enable_structure_preview
        if energy_source_mode is not None:
            mv_props["energy_source_mode"] = energy_source_mode
        if phase_stats is not None:
            mv_props["phase_stats"] = phase_stats
        if stable_entries is not None:
            mv_props["stable_entries"] = stable_entries
        if unstable_entries is not None:
            mv_props["unstable_entries"] = unstable_entries
        if highlighted_entries is not None:
            mv_props["highlighted_entries"] = highlighted_entries
        if selected_entry is not None:
            mv_props["selected_entry"] = selected_entry
        if tooltip is not None:
            mv_props["tooltip"] = tooltip
        if temperature is not None:
            mv_props["temperature"] = temperature
        if interpolate_temperature is not None:
            mv_props["interpolate_temperature"] = interpolate_temperature
        if max_interpolation_gap is not None:
            mv_props["max_interpolation_gap"] = max_interpolation_gap
        if gas_config is not None:
            mv_props["gas_config"] = gas_config
        if gas_pressures is not None:
            mv_props["gas_pressures"] = gas_pressures

        super().__init__(
            id=id,
            component="convex-hull/ConvexHull2D",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class ConvexHull3D(MatterViz):
    """3D convex hull phase diagram plot.

    Component key: ``convex-hull/ConvexHull3D``

    Events: on_point_click, on_point_hover, on_file_drop

    Unsupported snippets: children
    """

    def __init__(
        self,
        id=None,
        highlight_style: Any | None = None,
        entries: list | None = None,
        controls: dict | None = None,
        config: dict | None = None,
        fullscreen: bool | None = None,
        enable_fullscreen: bool | None = None,
        enable_info_pane: bool | None = None,
        label_threshold: float | None = None,
        show_stable: bool | None = None,
        show_unstable: bool | None = None,
        color_mode: Any | None = None,
        color_scale: Any | None = None,
        info_pane_open: bool | None = None,
        legend_pane_open: bool | None = None,
        max_hull_dist_show_phases: float | None = None,
        max_hull_dist_show_labels: float | None = None,
        show_stable_labels: bool | None = None,
        show_unstable_labels: bool | None = None,
        enable_click_selection: bool | None = None,
        enable_structure_preview: bool | None = None,
        energy_source_mode: Any | None = None,
        phase_stats: Any | None = None,
        stable_entries: list | None = None,
        unstable_entries: list | None = None,
        highlighted_entries: list | None = None,
        selected_entry: Any | None = None,
        tooltip: Any | None = None,
        temperature: float | None = None,
        interpolate_temperature: bool | None = None,
        max_interpolation_gap: float | None = None,
        gas_config: Any | None = None,
        gas_pressures: dict | None = None,
        show_hull_faces: bool | None = None,
        hull_face_opacity: float | None = None,
        hull_face_color_mode: Any | None = None,
        element_colors: dict | None = None,
        gizmo: dict | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if highlight_style is not None:
            mv_props["highlight_style"] = highlight_style
        if entries is not None:
            mv_props["entries"] = entries
        if controls is not None:
            mv_props["controls"] = controls
        if config is not None:
            mv_props["config"] = config
        if fullscreen is not None:
            mv_props["fullscreen"] = fullscreen
        if enable_fullscreen is not None:
            mv_props["enable_fullscreen"] = enable_fullscreen
        if enable_info_pane is not None:
            mv_props["enable_info_pane"] = enable_info_pane
        if label_threshold is not None:
            mv_props["label_threshold"] = label_threshold
        if show_stable is not None:
            mv_props["show_stable"] = show_stable
        if show_unstable is not None:
            mv_props["show_unstable"] = show_unstable
        if color_mode is not None:
            mv_props["color_mode"] = color_mode
        if color_scale is not None:
            mv_props["color_scale"] = color_scale
        if info_pane_open is not None:
            mv_props["info_pane_open"] = info_pane_open
        if legend_pane_open is not None:
            mv_props["legend_pane_open"] = legend_pane_open
        if max_hull_dist_show_phases is not None:
            mv_props["max_hull_dist_show_phases"] = max_hull_dist_show_phases
        if max_hull_dist_show_labels is not None:
            mv_props["max_hull_dist_show_labels"] = max_hull_dist_show_labels
        if show_stable_labels is not None:
            mv_props["show_stable_labels"] = show_stable_labels
        if show_unstable_labels is not None:
            mv_props["show_unstable_labels"] = show_unstable_labels
        if enable_click_selection is not None:
            mv_props["enable_click_selection"] = enable_click_selection
        if enable_structure_preview is not None:
            mv_props["enable_structure_preview"] = enable_structure_preview
        if energy_source_mode is not None:
            mv_props["energy_source_mode"] = energy_source_mode
        if phase_stats is not None:
            mv_props["phase_stats"] = phase_stats
        if stable_entries is not None:
            mv_props["stable_entries"] = stable_entries
        if unstable_entries is not None:
            mv_props["unstable_entries"] = unstable_entries
        if highlighted_entries is not None:
            mv_props["highlighted_entries"] = highlighted_entries
        if selected_entry is not None:
            mv_props["selected_entry"] = selected_entry
        if tooltip is not None:
            mv_props["tooltip"] = tooltip
        if temperature is not None:
            mv_props["temperature"] = temperature
        if interpolate_temperature is not None:
            mv_props["interpolate_temperature"] = interpolate_temperature
        if max_interpolation_gap is not None:
            mv_props["max_interpolation_gap"] = max_interpolation_gap
        if gas_config is not None:
            mv_props["gas_config"] = gas_config
        if gas_pressures is not None:
            mv_props["gas_pressures"] = gas_pressures
        if show_hull_faces is not None:
            mv_props["show_hull_faces"] = show_hull_faces
        if hull_face_opacity is not None:
            mv_props["hull_face_opacity"] = hull_face_opacity
        if hull_face_color_mode is not None:
            mv_props["hull_face_color_mode"] = hull_face_color_mode
        if element_colors is not None:
            mv_props["element_colors"] = element_colors
        if gizmo is not None:
            mv_props["gizmo"] = gizmo

        super().__init__(
            id=id,
            component="convex-hull/ConvexHull3D",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class ConvexHull4D(MatterViz):
    """4D convex hull phase diagram plot (for quaternary systems).

    Component key: ``convex-hull/ConvexHull4D``

    Events: on_point_click, on_point_hover, on_file_drop

    Unsupported snippets: children
    """

    def __init__(
        self,
        id=None,
        highlight_style: Any | None = None,
        entries: list | None = None,
        controls: dict | None = None,
        config: dict | None = None,
        fullscreen: bool | None = None,
        enable_fullscreen: bool | None = None,
        enable_info_pane: bool | None = None,
        label_threshold: float | None = None,
        show_stable: bool | None = None,
        show_unstable: bool | None = None,
        color_mode: Any | None = None,
        color_scale: Any | None = None,
        info_pane_open: bool | None = None,
        legend_pane_open: bool | None = None,
        max_hull_dist_show_phases: float | None = None,
        max_hull_dist_show_labels: float | None = None,
        show_stable_labels: bool | None = None,
        show_unstable_labels: bool | None = None,
        enable_click_selection: bool | None = None,
        enable_structure_preview: bool | None = None,
        energy_source_mode: Any | None = None,
        phase_stats: Any | None = None,
        stable_entries: list | None = None,
        unstable_entries: list | None = None,
        highlighted_entries: list | None = None,
        selected_entry: Any | None = None,
        tooltip: Any | None = None,
        temperature: float | None = None,
        interpolate_temperature: bool | None = None,
        max_interpolation_gap: float | None = None,
        gas_config: Any | None = None,
        gas_pressures: dict | None = None,
        show_hull_faces: bool | None = None,
        hull_face_opacity: float | None = None,
        hull_face_color_mode: Any | None = None,
        element_colors: dict | None = None,
        gizmo: dict | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if highlight_style is not None:
            mv_props["highlight_style"] = highlight_style
        if entries is not None:
            mv_props["entries"] = entries
        if controls is not None:
            mv_props["controls"] = controls
        if config is not None:
            mv_props["config"] = config
        if fullscreen is not None:
            mv_props["fullscreen"] = fullscreen
        if enable_fullscreen is not None:
            mv_props["enable_fullscreen"] = enable_fullscreen
        if enable_info_pane is not None:
            mv_props["enable_info_pane"] = enable_info_pane
        if label_threshold is not None:
            mv_props["label_threshold"] = label_threshold
        if show_stable is not None:
            mv_props["show_stable"] = show_stable
        if show_unstable is not None:
            mv_props["show_unstable"] = show_unstable
        if color_mode is not None:
            mv_props["color_mode"] = color_mode
        if color_scale is not None:
            mv_props["color_scale"] = color_scale
        if info_pane_open is not None:
            mv_props["info_pane_open"] = info_pane_open
        if legend_pane_open is not None:
            mv_props["legend_pane_open"] = legend_pane_open
        if max_hull_dist_show_phases is not None:
            mv_props["max_hull_dist_show_phases"] = max_hull_dist_show_phases
        if max_hull_dist_show_labels is not None:
            mv_props["max_hull_dist_show_labels"] = max_hull_dist_show_labels
        if show_stable_labels is not None:
            mv_props["show_stable_labels"] = show_stable_labels
        if show_unstable_labels is not None:
            mv_props["show_unstable_labels"] = show_unstable_labels
        if enable_click_selection is not None:
            mv_props["enable_click_selection"] = enable_click_selection
        if enable_structure_preview is not None:
            mv_props["enable_structure_preview"] = enable_structure_preview
        if energy_source_mode is not None:
            mv_props["energy_source_mode"] = energy_source_mode
        if phase_stats is not None:
            mv_props["phase_stats"] = phase_stats
        if stable_entries is not None:
            mv_props["stable_entries"] = stable_entries
        if unstable_entries is not None:
            mv_props["unstable_entries"] = unstable_entries
        if highlighted_entries is not None:
            mv_props["highlighted_entries"] = highlighted_entries
        if selected_entry is not None:
            mv_props["selected_entry"] = selected_entry
        if tooltip is not None:
            mv_props["tooltip"] = tooltip
        if temperature is not None:
            mv_props["temperature"] = temperature
        if interpolate_temperature is not None:
            mv_props["interpolate_temperature"] = interpolate_temperature
        if max_interpolation_gap is not None:
            mv_props["max_interpolation_gap"] = max_interpolation_gap
        if gas_config is not None:
            mv_props["gas_config"] = gas_config
        if gas_pressures is not None:
            mv_props["gas_pressures"] = gas_pressures
        if show_hull_faces is not None:
            mv_props["show_hull_faces"] = show_hull_faces
        if hull_face_opacity is not None:
            mv_props["hull_face_opacity"] = hull_face_opacity
        if hull_face_color_mode is not None:
            mv_props["hull_face_color_mode"] = hull_face_color_mode
        if element_colors is not None:
            mv_props["element_colors"] = element_colors
        if gizmo is not None:
            mv_props["gizmo"] = gizmo

        super().__init__(
            id=id,
            component="convex-hull/ConvexHull4D",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class IsobaricBinaryPhaseDiagram(MatterViz):
    """Binary isobaric phase diagram.

    Component key: ``phase-diagram/IsobaricBinaryPhaseDiagram``

    Events: on_phase_hover

    Unsupported snippets: tooltip
    """

    def __init__(
        self,
        id=None,
        config: dict | None = None,
        controls_open: bool | None = None,
        controls_props: dict | None = None,
        data: Any | None = None,
        display_temp_unit: Any | None = None,
        enable_export: bool | None = None,
        export_filename: str | None = None,
        export_pane_open: bool | None = None,
        fullscreen: bool | None = None,
        fullscreen_toggle: bool | None = None,
        hovered_region: Any | None = None,
        png_dpi: float | None = None,
        show_boundaries: bool | None = None,
        show_component_labels: bool | None = None,
        show_controls: bool | None = None,
        show_grid: bool | None = None,
        show_labels: bool | None = None,
        show_special_points: bool | None = None,
        x_axis: Any | None = None,
        y_axis: Any | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if config is not None:
            mv_props["config"] = config
        if controls_open is not None:
            mv_props["controls_open"] = controls_open
        if controls_props is not None:
            mv_props["controls_props"] = controls_props
        if data is not None:
            mv_props["data"] = data
        if display_temp_unit is not None:
            mv_props["display_temp_unit"] = display_temp_unit
        if enable_export is not None:
            mv_props["enable_export"] = enable_export
        if export_filename is not None:
            mv_props["export_filename"] = export_filename
        if export_pane_open is not None:
            mv_props["export_pane_open"] = export_pane_open
        if fullscreen is not None:
            mv_props["fullscreen"] = fullscreen
        if fullscreen_toggle is not None:
            mv_props["fullscreen_toggle"] = fullscreen_toggle
        if hovered_region is not None:
            mv_props["hovered_region"] = hovered_region
        if png_dpi is not None:
            mv_props["png_dpi"] = png_dpi
        if show_boundaries is not None:
            mv_props["show_boundaries"] = show_boundaries
        if show_component_labels is not None:
            mv_props["show_component_labels"] = show_component_labels
        if show_controls is not None:
            mv_props["show_controls"] = show_controls
        if show_grid is not None:
            mv_props["show_grid"] = show_grid
        if show_labels is not None:
            mv_props["show_labels"] = show_labels
        if show_special_points is not None:
            mv_props["show_special_points"] = show_special_points
        if x_axis is not None:
            mv_props["x_axis"] = x_axis
        if y_axis is not None:
            mv_props["y_axis"] = y_axis

        super().__init__(
            id=id,
            component="phase-diagram/IsobaricBinaryPhaseDiagram",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class XrdPlot(MatterViz):
    """X-ray diffraction pattern plot.

    Component key: ``xrd/XrdPlot``

    Events: on_file_drop
    """

    def __init__(
        self,
        id=None,
        allow_file_drop: bool | None = None,
        annotate_peaks: float | None = None,
        broadening_enabled: bool | None = None,
        broadening_params: Any | None = None,
        controls: Any | None = None,
        error_msg: str | None = None,
        hkl_format: Any | None = None,
        loading: bool | None = None,
        peak_width: float | None = None,
        show_angles: bool | None = None,
        wavelength: float | None = None,
        x_axis: Any | None = None,
        y_axis: Any | None = None,
        patterns: list[dict] | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if allow_file_drop is not None:
            mv_props["allow_file_drop"] = allow_file_drop
        if annotate_peaks is not None:
            mv_props["annotate_peaks"] = annotate_peaks
        if broadening_enabled is not None:
            mv_props["broadening_enabled"] = broadening_enabled
        if broadening_params is not None:
            mv_props["broadening_params"] = broadening_params
        if controls is not None:
            mv_props["controls"] = controls
        if error_msg is not None:
            mv_props["error_msg"] = error_msg
        if hkl_format is not None:
            mv_props["hkl_format"] = hkl_format
        if loading is not None:
            mv_props["loading"] = loading
        if peak_width is not None:
            mv_props["peak_width"] = peak_width
        if show_angles is not None:
            mv_props["show_angles"] = show_angles
        if wavelength is not None:
            mv_props["wavelength"] = wavelength
        if x_axis is not None:
            mv_props["x_axis"] = x_axis
        if y_axis is not None:
            mv_props["y_axis"] = y_axis
        if patterns is not None:
            mv_props["patterns"] = patterns

        super().__init__(
            id=id,
            component="xrd/XrdPlot",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Bands(MatterViz):
    """Band structure dispersion plot (phonon or electronic).

    Component key: ``spectral/Bands``

    Events: on_axis_change, on_error, on_fill_click, on_fill_hover, on_point_click, on_point_hover, on_ref_line_click, on_ref_line_hover

    Unsupported snippets: tooltip, user_content
    """

    def __init__(
        self,
        id=None,
        band_structs: dict | None = None,
        band_type: Any | None = None,
        controls: Any | None = None,
        current_x_value: float | None = None,
        data_loader: Any | None = None,
        error_bands: list | None = None,
        fermi_level: float | None = None,
        fill_regions: list | None = None,
        hover_config: dict | None = None,
        label_placement_config: dict | None = None,
        legend: Any | None = None,
        line_kwargs: Any | None = None,
        line_tween: Any | None = None,
        pan: Any | None = None,
        path_mode: Any | None = None,
        point_tween: Any | None = None,
        ref_lines: list | None = None,
        reference_frequency: float | None = None,
        ribbon_config: dict | None = None,
        selected_series_idx: int | None = None,
        series: list | None = None,
        show_legend: bool | None = None,
        styles: Any | None = None,
        tooltip_point: Any | None = None,
        x_axis: Any | None = None,
        x_positions: dict | None = None,
        y_axis: Any | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if band_structs is not None:
            mv_props["band_structs"] = band_structs
        if band_type is not None:
            mv_props["band_type"] = band_type
        if controls is not None:
            mv_props["controls"] = controls
        if current_x_value is not None:
            mv_props["current_x_value"] = current_x_value
        if data_loader is not None:
            mv_props["data_loader"] = data_loader
        if error_bands is not None:
            mv_props["error_bands"] = error_bands
        if fermi_level is not None:
            mv_props["fermi_level"] = fermi_level
        if fill_regions is not None:
            mv_props["fill_regions"] = fill_regions
        if hover_config is not None:
            mv_props["hover_config"] = hover_config
        if label_placement_config is not None:
            mv_props["label_placement_config"] = label_placement_config
        if legend is not None:
            mv_props["legend"] = legend
        if line_kwargs is not None:
            mv_props["line_kwargs"] = line_kwargs
        if line_tween is not None:
            mv_props["line_tween"] = line_tween
        if pan is not None:
            mv_props["pan"] = pan
        if path_mode is not None:
            mv_props["path_mode"] = path_mode
        if point_tween is not None:
            mv_props["point_tween"] = point_tween
        if ref_lines is not None:
            mv_props["ref_lines"] = ref_lines
        if reference_frequency is not None:
            mv_props["reference_frequency"] = reference_frequency
        if ribbon_config is not None:
            mv_props["ribbon_config"] = ribbon_config
        if selected_series_idx is not None:
            mv_props["selected_series_idx"] = selected_series_idx
        if series is not None:
            mv_props["series"] = series
        if show_legend is not None:
            mv_props["show_legend"] = show_legend
        if styles is not None:
            mv_props["styles"] = styles
        if tooltip_point is not None:
            mv_props["tooltip_point"] = tooltip_point
        if x_axis is not None:
            mv_props["x_axis"] = x_axis
        if x_positions is not None:
            mv_props["x_positions"] = x_positions
        if y_axis is not None:
            mv_props["y_axis"] = y_axis

        super().__init__(
            id=id,
            component="spectral/Bands",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Dos(MatterViz):
    """Density of states plot (electronic or phonon).

    Component key: ``spectral/Dos``

    Events: on_axis_change, on_error, on_fill_click, on_fill_hover, on_point_click, on_point_hover, on_ref_line_click, on_ref_line_hover

    Unsupported snippets: tooltip, user_content
    """

    def __init__(
        self,
        id=None,
        controls: Any | None = None,
        current_x_value: float | None = None,
        data_loader: Any | None = None,
        doses: dict | None = None,
        error_bands: list | None = None,
        fermi_level: float | None = None,
        fill_regions: list | None = None,
        hover_config: dict | None = None,
        hovered_frequency: float | None = None,
        label_placement_config: dict | None = None,
        legend: Any | None = None,
        line_tween: Any | None = None,
        normalize: Any | None = None,
        orientation: Any | None = None,
        pan: Any | None = None,
        pdos_filter: list[str] | None = None,
        pdos_type: Any | None = None,
        point_tween: Any | None = None,
        ref_lines: list | None = None,
        reference_frequency: float | None = None,
        selected_series_idx: int | None = None,
        series: list | None = None,
        show_controls: bool | None = None,
        show_legend: bool | None = None,
        show_normalize_control: bool | None = None,
        show_sigma_control: bool | None = None,
        show_units_control: bool | None = None,
        sigma: float | None = None,
        sigma_range: list | None = None,
        spin_mode: Any | None = None,
        stack: bool | None = None,
        styles: Any | None = None,
        tooltip_point: Any | None = None,
        units: Any | None = None,
        x_axis: Any | None = None,
        y_axis: Any | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if controls is not None:
            mv_props["controls"] = controls
        if current_x_value is not None:
            mv_props["current_x_value"] = current_x_value
        if data_loader is not None:
            mv_props["data_loader"] = data_loader
        if doses is not None:
            mv_props["doses"] = doses
        if error_bands is not None:
            mv_props["error_bands"] = error_bands
        if fermi_level is not None:
            mv_props["fermi_level"] = fermi_level
        if fill_regions is not None:
            mv_props["fill_regions"] = fill_regions
        if hover_config is not None:
            mv_props["hover_config"] = hover_config
        if hovered_frequency is not None:
            mv_props["hovered_frequency"] = hovered_frequency
        if label_placement_config is not None:
            mv_props["label_placement_config"] = label_placement_config
        if legend is not None:
            mv_props["legend"] = legend
        if line_tween is not None:
            mv_props["line_tween"] = line_tween
        if normalize is not None:
            mv_props["normalize"] = normalize
        if orientation is not None:
            mv_props["orientation"] = orientation
        if pan is not None:
            mv_props["pan"] = pan
        if pdos_filter is not None:
            mv_props["pdos_filter"] = pdos_filter
        if pdos_type is not None:
            mv_props["pdos_type"] = pdos_type
        if point_tween is not None:
            mv_props["point_tween"] = point_tween
        if ref_lines is not None:
            mv_props["ref_lines"] = ref_lines
        if reference_frequency is not None:
            mv_props["reference_frequency"] = reference_frequency
        if selected_series_idx is not None:
            mv_props["selected_series_idx"] = selected_series_idx
        if series is not None:
            mv_props["series"] = series
        if show_controls is not None:
            mv_props["show_controls"] = show_controls
        if show_legend is not None:
            mv_props["show_legend"] = show_legend
        if show_normalize_control is not None:
            mv_props["show_normalize_control"] = show_normalize_control
        if show_sigma_control is not None:
            mv_props["show_sigma_control"] = show_sigma_control
        if show_units_control is not None:
            mv_props["show_units_control"] = show_units_control
        if sigma is not None:
            mv_props["sigma"] = sigma
        if sigma_range is not None:
            mv_props["sigma_range"] = sigma_range
        if spin_mode is not None:
            mv_props["spin_mode"] = spin_mode
        if stack is not None:
            mv_props["stack"] = stack
        if styles is not None:
            mv_props["styles"] = styles
        if tooltip_point is not None:
            mv_props["tooltip_point"] = tooltip_point
        if units is not None:
            mv_props["units"] = units
        if x_axis is not None:
            mv_props["x_axis"] = x_axis
        if y_axis is not None:
            mv_props["y_axis"] = y_axis

        super().__init__(
            id=id,
            component="spectral/Dos",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class ScatterPlot(MatterViz):
    """General-purpose scatter plot with customizable axes and tooltips.

    Component key: ``plot/ScatterPlot``

    Events: on_axis_change, on_error, on_fill_click, on_fill_hover, on_point_click, on_point_hover, on_ref_line_click, on_ref_line_hover

    Unsupported snippets: tooltip, user_content
    """

    def __init__(
        self,
        id=None,
        controls: Any | None = None,
        current_x_value: float | None = None,
        data_loader: Any | None = None,
        error_bands: list | None = None,
        fill_regions: list | None = None,
        hover_config: dict | None = None,
        label_placement_config: dict | None = None,
        legend: Any | None = None,
        line_tween: Any | None = None,
        pan: Any | None = None,
        point_tween: Any | None = None,
        ref_lines: list | None = None,
        selected_series_idx: int | None = None,
        series: list | None = None,
        styles: Any | None = None,
        tooltip_point: Any | None = None,
        x_axis: Any | None = None,
        y_axis: Any | None = None,
        height: Any | None = None,
        width: Any | None = None,
        color_scale: Any | None = None,
        size_scale: Any | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if controls is not None:
            mv_props["controls"] = controls
        if current_x_value is not None:
            mv_props["current_x_value"] = current_x_value
        if data_loader is not None:
            mv_props["data_loader"] = data_loader
        if error_bands is not None:
            mv_props["error_bands"] = error_bands
        if fill_regions is not None:
            mv_props["fill_regions"] = fill_regions
        if hover_config is not None:
            mv_props["hover_config"] = hover_config
        if label_placement_config is not None:
            mv_props["label_placement_config"] = label_placement_config
        if legend is not None:
            mv_props["legend"] = legend
        if line_tween is not None:
            mv_props["line_tween"] = line_tween
        if pan is not None:
            mv_props["pan"] = pan
        if point_tween is not None:
            mv_props["point_tween"] = point_tween
        if ref_lines is not None:
            mv_props["ref_lines"] = ref_lines
        if selected_series_idx is not None:
            mv_props["selected_series_idx"] = selected_series_idx
        if series is not None:
            mv_props["series"] = series
        if styles is not None:
            mv_props["styles"] = styles
        if tooltip_point is not None:
            mv_props["tooltip_point"] = tooltip_point
        if x_axis is not None:
            mv_props["x_axis"] = x_axis
        if y_axis is not None:
            mv_props["y_axis"] = y_axis
        if height is not None:
            mv_props["height"] = height
        if width is not None:
            mv_props["width"] = width
        if color_scale is not None:
            mv_props["color_scale"] = color_scale
        if size_scale is not None:
            mv_props["size_scale"] = size_scale

        super().__init__(
            id=id,
            component="plot/ScatterPlot",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class Histogram(MatterViz):
    """Histogram plot for data distributions.

    Component key: ``plot/Histogram``

    Events: on_axis_change, on_error, on_ref_line_click, on_ref_line_hover, on_series_toggle

    Unsupported snippets: controls_extra, tooltip
    """

    def __init__(
        self,
        id=None,
        bar: Any | None = None,
        bins: float | None = None,
        data_loader: Any | None = None,
        legend: Any | None = None,
        mode: Any | None = None,
        pan: Any | None = None,
        ref_lines: list | None = None,
        selected_property: str | None = None,
        series: list | None = None,
        show_legend: bool | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if bar is not None:
            mv_props["bar"] = bar
        if bins is not None:
            mv_props["bins"] = bins
        if data_loader is not None:
            mv_props["data_loader"] = data_loader
        if legend is not None:
            mv_props["legend"] = legend
        if mode is not None:
            mv_props["mode"] = mode
        if pan is not None:
            mv_props["pan"] = pan
        if ref_lines is not None:
            mv_props["ref_lines"] = ref_lines
        if selected_property is not None:
            mv_props["selected_property"] = selected_property
        if series is not None:
            mv_props["series"] = series
        if show_legend is not None:
            mv_props["show_legend"] = show_legend

        super().__init__(
            id=id,
            component="plot/Histogram",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )

class RdfPlot(MatterViz):
    """Radial distribution function (RDF) plot.

    Component key: ``rdf/RdfPlot``

    Events: on_file_drop
    """

    def __init__(
        self,
        id=None,
        cutoff: float | None = None,
        drag_dropped: list | None = None,
        dragging: bool | None = None,
        enable_drop: bool | None = None,
        error_msg: str | None = None,
        loading: bool | None = None,
        mode: Any | None = None,
        n_bins: int | None = None,
        patterns: list | None = None,
        pbc: Any | None = None,
        show_reference_line: bool | None = None,
        structures: dict | None = None,
        x_axis: dict | None = None,
        y_axis: dict | None = None,
        mv_props: dict | None = None,
        set_props: list[str] | None = None,
        float32_props: list[str] | None = None,
        event_props: list[str] | None = None,
        last_event: dict | None = None,
        className: str | None = None,
        style: dict | None = None,
        **kwargs,
    ):
        if mv_props is None:
            mv_props = {}
        if cutoff is not None:
            mv_props["cutoff"] = cutoff
        if drag_dropped is not None:
            mv_props["drag_dropped"] = drag_dropped
        if dragging is not None:
            mv_props["dragging"] = dragging
        if enable_drop is not None:
            mv_props["enable_drop"] = enable_drop
        if error_msg is not None:
            mv_props["error_msg"] = error_msg
        if loading is not None:
            mv_props["loading"] = loading
        if mode is not None:
            mv_props["mode"] = mode
        if n_bins is not None:
            mv_props["n_bins"] = n_bins
        if patterns is not None:
            mv_props["patterns"] = patterns
        if pbc is not None:
            mv_props["pbc"] = pbc
        if show_reference_line is not None:
            mv_props["show_reference_line"] = show_reference_line
        if structures is not None:
            mv_props["structures"] = structures
        if x_axis is not None:
            mv_props["x_axis"] = x_axis
        if y_axis is not None:
            mv_props["y_axis"] = y_axis

        super().__init__(
            id=id,
            component="rdf/RdfPlot",
            mv_props=mv_props,
            set_props=set_props,
            float32_props=float32_props,
            event_props=event_props,
            last_event=last_event,
            className=className,
            style=style,
            **kwargs,
        )
